### ISSUE TITLE
Android: Unable to Pinch to Zoom

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-gl-native#10101]
Since Using The Below Dependency I Am Now Unable To Pinch To Zoom On My Android 4.1.2 Motorola TC55 Device.

_This originates from the PR #10026_ 

**Screenshot** - _I'm Able To Two Finger Double Tap To Zoom Out and Single Finger Double Tap To Zoom In_

![mapview_pinchtozoom_4_1_2](https://user-images.githubusercontent.com/32104383/31082007-91e9f654-a785-11e7-817e-013560d093dc.gif)

**app.gradle**
```
// Mapbox Maps SDK
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') {
        transitive=true
    }
```

**LogCat**
```
10-02 15:16:19.148 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.198 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.228 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.248 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.278 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.328 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.358 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.408 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.448 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.468 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.519 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.549 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.599 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.619 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.659 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.699 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:19.719 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.340 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.360 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.390 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.450 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.470 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.520 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.540 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.570 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.600 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.630 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.650 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.680 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.720 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.740 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.780 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.810 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.840 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.860 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:39.880 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:40.321 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.331 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.361 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.431 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.461 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.501 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.551 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.581 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.621 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.651 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.681 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.711 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.731 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.761 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.801 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.832 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.862 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.922 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.942 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:16:59.972 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:00.032 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:13.856 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:13.907 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:13.967 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.007 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.097 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.137 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.177 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.237 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.277 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.297 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.327 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.357 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.397 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.467 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.487 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.507 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.537 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.587 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.647 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.667 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.737 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.757 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:14.938 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.018 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.058 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.098 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.148 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.168 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.188 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.238 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.258 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.308 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.358 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.448 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.468 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.498 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.518 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.668 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.698 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
10-02 15:17:15.769 17650-17650/uk.co.ainscough.routeinfo E/TileRenderer: glEndTilingQCOM: 0x502
```

**Comment by tobrun** [comment]
@Danny-James in https://github.com/mapbox/mapbox-gl-native/pull/10134 the values for determining gesture interactions were revisited. Would you be able to test this out when that is merged with the 5.2.0-SNAPSHOT build? Thank you

**Comment by Danny-James** [comment]
@tobrun Please let me know when ready to test.

**Comment by Danny-James** [comment]
@tobrun did you manage to take another look at this?

**Comment by Danny-James** [comment]
@tobrun Do we have an ETA on this release?

**Comment by tobrun** [comment]
@Danny-James apologies for not getting back to you. I'm having hard time reproducing this issue, been testing this on a range of devices but these don't show the issue in OP. Is this behaviour instantly reproducible or does it show after a couple of actions? If the latter, could you add which?

**Comment by tobrun** [comment]
@Danny-James can you rotate if this issue of not pinch zooming is showing? Were you able to retest this with any of the 5.2.0-beta.1 or beta.2?

**Comment by Danny-James** [comment]
Let me load up the project and change dependency will come back to you within the next 30 minutes.

**Comment by Danny-James** [comment]
Testing This Now @tobrun I do recall trying `5.2.0-beta.1` and it would did keep crashing my app, let me confirm this, I'm going to try `beta2`

**Comment by Danny-James** [comment]
@tobrun See Below Error

**LogCat**
```
10-24 17:26:16.492 6025-6025/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         java.lang.NoSuchMethodError: com.mapbox.mapboxsdk.style.layers.PropertyFactory.lineWidth
                                                                             at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addNavigationRouteLayer(NavigationMapRoute.java:371)
                                                                             at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:179)
                                                                             at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:156)
                                                                             at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:135)
                                                                             at uk.co.ainscough.routeinfo.ActivityNavigationMap.drawRoute(ActivityNavigationMap.java:369)
                                                                             at uk.co.ainscough.routeinfo.ActivityNavigationMap.onResponse(ActivityNavigationMap.java:306)
                                                                             at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                             at android.os.Handler.handleCallback(Handler.java:615)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                             at dalvik.system.NativeStart.main(Native Method)
10-24 17:26:16.502 6025-6160/uk.co.ainscough.routeinfo D/CrashlyticsCore: Attempting to send crash report at time of crash...
```

***ActivityNavigationMap.java***
```
Line 367:            // Draw the route on the map
Line 368:            Log.d(TAG, "Create NavigationMapRoute();");
Line 369:            navigationMapRoute = new NavigationMapRoute(null, mapView, this.mapboxMap, R.style.NavigationMapRoute);
Line 370:            navigationMapRoute.addRoute(currentRoute);
```

**Comment by tobrun** [comment]
Potential fix for that crash in https://github.com/mapbox/mapbox-gl-native/pull/10253 though having a hard time tracking down the GPU found in the Motorola TC55.

**Comment by Danny-James** [comment]
Is this something that will be pushed into a SnapShot or something I need to do?

@tobrun I took out the navigation route to get the map to load, still no pinch to zoom and the beta.2 crashes my app when loading Navigation UI.

I get one bug fixed then I get 2-3 more, and I have a deadline for the app I'm developing.

**Comment by tobrun** [comment]
@Danny-James 
We released a new version of the nav sdk 0.6.3 that is compatible with the 5.2.0-beta.3 version of the map sdk. I figured out what your issue is and will be handled with #10202, should be included in the next beta.

**Comment by Danny-James** [comment]
@tobrun Thanks very much will give this a go tomorrow and will report back any issues, hopefully none 👍

**Comment by Danny-James** [comment]
@tobrun - Crashlytics Report (http://crashes.to/s/d9b2533481f)

See Below, I'm now using;
```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar') {
        transitive=true
    }
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
```


**Error**
```
10-31 14:34:34.346 19617-19617/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.NoSuchMethodError: com.mapbox.mapboxsdk.style.layers.PropertyFactory.lineWidth
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addNavigationRouteLayer(NavigationMapRoute.java:374)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:179)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:156)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:135)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.drawRoute(ActivityNavigationMap.java:369)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.onResponse(ActivityNavigationMap.java:306)
                                                                               at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                               at android.os.Handler.handleCallback(Handler.java:615)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                               at android.os.Looper.loop(Looper.java:137)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                               at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Danny-James** [comment]
@tobrun Also getting the same crash on Android 8.1.0 Google Pixel

**Comment by Danny-James** [comment]
@cammace You have closed a similar issue shown above [#Comment](https://github.com/mapbox/mapbox-gl-native/issues/10101#issuecomment-340765772) - [#437](https://github.com/mapbox/mapbox-navigation-android/issues/437#event-1330009022) can you expand on what you mean please?

**Comment by tobrun** [comment]
The original issue is fixed with #10202 and is testable with `5.2.0-beta.4`. Feel free to test that out and provide any feedback.

Currently the best way to test all components together is using: 
 > 5.2.0-beta.4 from the maps sdk
 0.2.0-SNAPSHOT from the location layer plugin
 0.6.3 from the nav sdk

**Comment by Danny-James** [comment]
Thanks @tobrun Giving this ago now.

**Comment by Danny-James** [comment]
@tobrun still getting an error using Google Pixel 8.1.0:

```
11-07 17:56:50.901 22720-22720/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: uk.co.ainscough.routeinfo, PID: 22720
                                                                           java.lang.NoSuchMethodError: No static method lineWidth(Lcom/mapbox/mapboxsdk/style/functions/CameraFunction;)Lcom/mapbox/mapboxsdk/style/layers/PropertyValue; in class Lcom/mapbox/mapboxsdk/style/layers/PropertyFactory; or its super classes (declaration of 'com.mapbox.mapboxsdk.style.layers.PropertyFactory' appears in /data/app/uk.co.ainscough.routeinfo-M5DKZvPrzAOWILd96cIe-A==/split_lib_dependencies_apk.apk!classes2.dex)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addNavigationRouteLayer(NavigationMapRoute.java:374)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:179)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:156)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:135)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.drawRoute(ActivityNavigationMap.java:371)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.onResponse(ActivityNavigationMap.java:299)
                                                                               at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                               at android.os.Handler.handleCallback(Handler.java:790)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:164)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Failing Code**
```
navigationMapRoute = new NavigationMapRoute(null, mapView, this.mapboxMap, R.style.NavigationMapRoute);
navigationMapRoute.addRoute(currentRoute);
```

**Gradle 3.0**
```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "uk.co.ainscough.routeinfo"
        minSdkVersion 15
        targetSdkVersion 26
        multiDexEnabled true
        versionCode 2
        versionName "2.0.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.google.com' }
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    compile 'com.google.dagger:dagger:2.5'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.5'

    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile files('libs/xstream-1.4.7.jar')

    // Mapbox Maps SDK
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.4@aar') {
        transitive=true
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.3') {
        transitive = true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'

    // Support Library Dependencies.
    compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.android.support:design:26.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:26.0.1'

    compile 'com.google.android.gms:play-services-maps:11.0.4';
    compile 'junit:junit:4.12'

    compile 'com.jakewharton:butterknife:8.6.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
    compile 'com.jakewharton:butterknife-compiler:8.6.0'

    annotationProcessor 'android.arch.lifecycle:compiler:1.0.0-alpha9-1'

    // Compile MultiDex Support
    compile 'com.android.support:multidex:1.0.2'

    // Crashlytics Dependency to Report Crash Reports.
    compile('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
        transitive = true;
    }

}
```

**Comment by Danny-James** [comment]
@tobrun is this something to do with `NAV SDK` or `MAP SDK`?

**Comment by tobrun** [comment]
This has to do with `mapbox-android-navigation-ui` still using location layer 0.1.0 instead of 0.2.0-SNAPSHOT. For now only older versions of the map sdk are compatible.

**Comment by tobrun** [comment]
See https://github.com/mapbox/mapbox-navigation-android/issues/468.

**Comment by Danny-James** [comment]
@tobrun I'm now including `0.2.0-SNAPSHOT` see below my gradle.

```
    // Mapbox Maps SDK
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.4@aar') {
        transitive=true
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.3') {
        transitive = true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
```

However, i'm still getting the error I reported, do i need to exclude the location-layer-plugin from the `NAV SDK`? - If so how do i do this?

```
11-08 09:23:54.285 18294-18294/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: uk.co.ainscough.routeinfo, PID: 18294
                                                                           java.lang.NoSuchMethodError: No static method lineWidth(Lcom/mapbox/mapboxsdk/style/functions/CameraFunction;)Lcom/mapbox/mapboxsdk/style/layers/PropertyValue; in class Lcom/mapbox/mapboxsdk/style/layers/PropertyFactory; or its super classes (declaration of 'com.mapbox.mapboxsdk.style.layers.PropertyFactory' appears in /data/app/uk.co.ainscough.routeinfo-23lFokdTJ9p11_O9tN5hTQ==/split_lib_dependencies_apk.apk!classes2.dex)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addNavigationRouteLayer(NavigationMapRoute.java:374)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:179)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:156)
                                                                               at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:135)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.drawRoute(ActivityNavigationMap.java:371)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.onResponse(ActivityNavigationMap.java:299)
                                                                               at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                               at android.os.Handler.handleCallback(Handler.java:790)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:164)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
