### ISSUE TITLE
TelemtryService Android Crash - Runtime Exception

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#11955]
Hi we have a runtime exception on mapbox latest version on Android.

`Fatal Exception: java.lang.RuntimeException
Unable to start service com.mapbox.android.telemetry.TelemetryService@6e0bcc with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
android.app.ActivityThread.handleServiceArgs`

**Platform: Android
**Mapbox SDK version: 6.1.1

### Steps to trigger behavior

 1. Just use Mapbox in production and have proper proguard rules.

### Expected behavior

- Not to crash

### Actual behavior

- Work as expected, but currently crashing

**Comment by LukasPaczos** [comment]
Would you mind sharing some details about devices that you are seeing this crashes on?

@electrostat, can this issue be solved by `v3.1.1` of the telemetry library that's a part of `v6.1.2` of the Maps SDK?

**Comment by nikiizvorski** [comment]
Nope issue still persist. Here are device information:

`com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000 (Unknown Source:41)
com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry (Unknown Source:46)
com.mapbox.mapboxsdk.maps.Telemetry.initialize (Unknown Source:30)
com.mapbox.mapboxsdk.Mapbox.getInstance (Unknown Source:49)

Caused by java.lang.IllegalStateException
Not allowed to start service Intent { cmp=app/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{5cdd138 u0a330 RCVR idle procs:1 seq(0,0,0)}

`

**Comment by electrostat** [comment]
This is being handled here: https://github.com/mapbox/mapbox-events-android/pull/152

**Comment by nikiizvorski** [comment]
I believe these events are not being seen lately on 6.1.3. Need to be tested more. It combines with another post to remove telemetry from the application.

`<meta-data android:name="com.mapbox.EnableEvents" android:value="false" />`

**Comment by tobrun** [comment]
Haven't heard about any issues in the latest 6.2.1 release. Closing, feel free to reach out if you hit any issues.

**Comment by nininea1** [comment]
I have the same issue , when I try to load map second time ( in second page) 

> 
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.5.0'
>     implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.8.2'

from debug console :

> A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x67622d736619 in tid 7478 (FinalizerDaemon)

from logcat:

 
> 09-27 16:44:51.550 7778-7778/com.wandio.ttcmobile E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.wandio.ttcmobile, PID: 7778
>     java.lang.RuntimeException: Unable to create service com.mapbox.android.telemetry.TelemetryService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
>         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2878)
>         at android.app.ActivityThread.access$2200(ActivityThread.java:152)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:135)
>         at android.app.ActivityThread.main(ActivityThread.java:5538)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:372)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
>      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
>         at android.support.v4.content.PermissionChecker.checkSelfPermission(PermissionChecker.java:134)
>         at com.mapbox.android.telemetry.TelemetryService.locationPermissionCheck(TelemetryService.java:279)
>         at com.mapbox.android.telemetry.TelemetryService.connectLocationEngine(TelemetryService.java:181)
>         at com.mapbox.android.telemetry.TelemetryService.registerLocationReceiver(TelemetryService.java:171)
>         at com.mapbox.android.telemetry.TelemetryService.createLocationReceiver(TelemetryService.java:167)
>         at com.mapbox.android.telemetry.TelemetryService.onCreate(TelemetryService.java:47)
>         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2858)
>         at android.app.ActivityThread.access$2200(ActivityThread.java:152) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:135) 
>         at android.app.ActivityThread.main(ActivityThread.java:5538) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at java.lang.reflect.Method.invoke(Method.java:372) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by nininea1** [comment]
today, I updated 6.2.1 to 6.5.0  and got exceptions...

**Comment by Rolf737** [comment]
Hey guys, 

I have been getting the same error. 6.5.0 release.

Fatal Exception: java.lang.RuntimeException: Unable to create service com.mapbox.android.telemetry.TelemetryService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3716) 
at android.app.ActivityThread.access$2000(ActivityThread.java:218) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:145) 
at android.app.ActivityThread.main(ActivityThread.java:7007) 
at java.lang.reflect.Method.invoke(Method.java) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference 
at android.support.v4.content.PermissionChecker.checkSelfPermission(PermissionChecker.java:131) 
at com.mapbox.android.telemetry.TelemetryService.locationPermissionCheck(TelemetryService.java:279) 
at com.mapbox.android.telemetry.TelemetryService.connectLocationEngine(TelemetryService.java:181) 
at com.mapbox.android.telemetry.TelemetryService.registerLocationReceiver(TelemetryService.java:171) 
at com.mapbox.android.telemetry.TelemetryService.createLocationReceiver(TelemetryService.java:167) 
at com.mapbox.android.telemetry.TelemetryService.onCreate(TelemetryService.java:47) 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3706) 
at android.app.ActivityThread.access$2000(ActivityThread.java:218) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1827) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:145) 
at android.app.ActivityThread.main(ActivityThread.java:7007) 
at java.lang.reflect.Method.invoke(Method.java) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 

Build config items: 
mapboxSdkVersion = "6.5.0" 
mapboxNavigation = "0.17.0" 
mapboxDecoder = "1.0.0" 
mapboxLocationLayer = "0.7.2" 

implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapboxSdkVersion" 
implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapboxNavigation" 
implementation("com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapboxNavigation") { 
transitive = true 
} 
implementation("com.mapbox.mapboxsdk:mapbox-android-geocoder:$mapboxDecoder") { 
transitive = true 
} 
implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:$mapboxLocationLayer" 

We've had a couple hundred occurrences in the last week alone. This is our #1 crash.

Seems to happen to a variety of devices running Android 5.X. Actually, yeah... as I'm going through the reports they seem to all be 5.X...

Thanks,
Rolf

**Comment by LukasPaczos** [comment]
@electrostat are there any actions required or is this handled in the `3.3.0` of the telemetry library?

**Comment by electrostat** [comment]
@LukasPaczos this has not been address in `3.3.0` it's on the list of things to work on this sprint and see if we can nail this down. I would recommend they try the latest sdk, since there is a bug fix related to Android 5.1 and below builds. Just for testing sakes and to make sure all of our bases are covered.

**Comment by Rolf737** [comment]
I updated to 6.6.0, did a full clean / rebuild, and got this as soon as I tried to nav:

2018-10-15 14:48:43.448 21846-21846/com.reverllc.rever E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.reverllc.rever, PID: 21846
java.lang.NoSuchMethodError: No direct method <init>(Ljava/util/Date;IIILjava/lang/String;Ljava/lang/String;ILjava/lang/String;DDLjava/lang/String;Ljava/lang/String;ZLjava/lang/String;I)V in class Lcom/mapbox/android/telemetry/NavigationMetadata; or its super classes (declaration of 'com.mapbox.android.telemetry.NavigationMetadata' appears in /data/app/com.reverllc.rever-yZS8VA1EuCTNYxCj-L3Akg==/base.apk:classes18.dex)
at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.departEvent(NavigationMetricsWrapper.java:175)
at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.onRouteProgressUpdate(NavigationTelemetry.java:105)
at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.sendMetricProgressUpdate(NavigationEventDispatcher.java:186)
at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:142)
at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:34)
at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:119)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

I then tried updating all the other mapbox deps to their latest versions, rebuilding again, but the fatal exception still occurred.

I just went back to 6.5.0, rebuilt again, and the exception is gone (just making sure it's not some weird build thing on my side).

**Comment by tobrun** [comment]
@Rolf could you add your Mapbox dependencies? This looks like one a dependency got overwritten and as result it can't find certain classes

**Comment by Rolf737** [comment]
Adding dependency info:

My first attempt with 6.6.0 was only updating the SDK:
    mapboxSdkVersion = "6.6.0"
    mapboxNavigation = "0.17.0"
    mapboxDecoder = "1.0.0"
    mapboxLocationLayer = "0.7.2"

    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapboxSdkVersion"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapboxNavigation"
    implementation("com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapboxNavigation") {
        transitive = true
    }
    implementation("com.mapbox.mapboxsdk:mapbox-android-geocoder:$mapboxDecoder") {
        transitive = true
    }
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:$mapboxLocationLayer"

I had the exception so I went to see what the latest versions of the other mapbox deps were, and tried this (added in right spots):
 
    maven { url 'https://mapbox.bintray.com/mapbox' }

    mapboxSdkVersion = "6.6.0"
    mapboxNavigation = "0.21.0"
    mapboxDecoder = "1.0.0"
    mapboxLocationLayer = "0.10.0"

**Comment by paulkugaev** [comment]
Same here. Same dependencies, same versions

```
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/util/Date;IIILjava/lang/String;Ljava/lang/String;ILjava/lang/String;DDLjava/lang/String;Ljava/lang/String;ZLjava/lang/String;I)V in class Lcom/mapbox/android/telemetry/NavigationMetadata; or its super classes (declaration of 'com.mapbox.android.telemetry.NavigationMetadata' appears in /data/app/by.iesplus.shturman-Owk3ocy8n2wIHtMbUrI15A==/split_lib_dependencies_apk.apk)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.departEvent(NavigationMetricsWrapper.java:175)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.onRouteProgressUpdate(NavigationTelemetry.java:105)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.sendMetricProgressUpdate(NavigationEventDispatcher.java:186)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:142)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:34)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:119)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tobrun** [comment]
@paulkugaev can you bump navigation to v0.22.0 and maps sdk to v.6.6.2?

**Comment by paulkugaev** [comment]
@tobrun few minutes please

**Comment by paulkugaev** [comment]
@tobrun works like a charm!

**Comment by Rolf737** [comment]
Still getting the TelemetryService crash on Android 5.X devices after updating:

    mapboxSdkVersion = "6.6.2"
    mapboxNavigation = "0.22.0"
    mapboxDecoder = "1.0.0"
    mapboxLocationLayer = "0.10.0"

    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapboxSdkVersion"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapboxNavigation"
    implementation("com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapboxNavigation") {
        transitive = true
    }
    implementation("com.mapbox.mapboxsdk:mapbox-android-geocoder:$mapboxDecoder") {
        transitive = true
    }
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:$mapboxLocationLayer"

Fatal Exception: java.lang.RuntimeException: Unable to create service com.mapbox.android.telemetry.TelemetryService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2795)
       at android.app.ActivityThread.access$1700(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5298)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.support.v4.content.PermissionChecker.checkSelfPermission(PermissionChecker.java:131)
       at com.mapbox.android.telemetry.TelemetryService.locationPermissionCheck(TelemetryService.java:279)
       at com.mapbox.android.telemetry.TelemetryService.connectLocationEngine(TelemetryService.java:181)
       at com.mapbox.android.telemetry.TelemetryService.registerLocationReceiver(TelemetryService.java:171)
       at com.mapbox.android.telemetry.TelemetryService.createLocationReceiver(TelemetryService.java:167)
       at com.mapbox.android.telemetry.TelemetryService.onCreate(TelemetryService.java:47)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2785)
       at android.app.ActivityThread.access$1700(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5298)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by LukasPaczos** [comment]
@Rolf737 based on the traces, this should be resolved with the `v6.6.4` of the Maps SDK, see https://github.com/mapbox/mapbox-gl-native/issues/13257. Wouldn't you mind retesting?

**Comment by Rolf737** [comment]
Tried this:

    mapboxSdkVersion = "6.6.5"
    mapboxNavigation = "0.22.0"
    mapboxDecoder = "1.0.0"
    mapboxLocationLayer = "0.11.0"

    implementation "com.mapbox.mapboxsdk:mapbox-android-sdk:$mapboxSdkVersion"
    implementation "com.mapbox.mapboxsdk:mapbox-android-navigation:$mapboxNavigation"
    implementation("com.mapbox.mapboxsdk:mapbox-android-navigation-ui:$mapboxNavigation") {
        transitive = true
    }
    implementation("com.mapbox.mapboxsdk:mapbox-android-geocoder:$mapboxDecoder") {
        transitive = true
    }
    implementation "com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:$mapboxLocationLayer"

But I got this:

Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:3.2.0

**Comment by Rolf737** [comment]
A little googling and I added this repo, which got rid of that error:
    maven { url 'https://mapbox.bintray.com/mapbox' }

**Comment by Rolf737** [comment]
And now a similar crash is affecting a larger percentage of users, on various Android OS versions...

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at com.mapbox.android.telemetry.TelemetryUtils.obtainApplicationState(TelemetryUtils.java:103)
       at com.mapbox.android.telemetry.LocationEvent.<init>(LocationEvent.java:44)
       at com.mapbox.android.telemetry.LocationMapper.createLocationEvent(LocationMapper.java:32)
       at com.mapbox.android.telemetry.LocationMapper.from(LocationMapper.java:18)
       at com.mapbox.android.telemetry.LocationReceiver.sendEvent(LocationReceiver.java:47)
       at com.mapbox.android.telemetry.LocationReceiver.onReceive(LocationReceiver.java:26)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by LukasPaczos** [comment]
Which version are you using @Rolf737? This one should be fixed in the `v6.6.7` or the upcoming `v6.7.1`. Unfortunately, `v6.7.0` might still be affected.

**Comment by Rolf737** [comment]
6.6.5, as in my above post. 

If I add this to my manifest, will it disable the Telemetry service and get rid of these crashes? This is my #1 crash by far and it's gotten much worse since upgrading to 6.6.5.

<meta-data android:name="com.mapbox.EnableEvents" android:value="false" />

**Comment by LukasPaczos** [comment]
@mf16 This one should be fixed in `v6.7.1`, see https://github.com/mapbox/mapbox-events-android/pull/272.
