### ISSUE TITLE
MapBox 6.1.3 Android Telemetry Crash Persist

### ISSUE THREAD

**Issue by nikiizvorski** [mapbox/mapbox-gl-native#11994]
Hi we are currently experiencing the Telemetry issues on MapBox once again. 

`05-23 15:46:14.092 25783-25783/co.airdates.buckleup E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.airdates.buckleup, PID: 25783
    java.lang.ExceptionInInitializerError
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
        at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
        at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
        at App.setMap(BuckleUp.java:71)
        at App.onCreate(BuckleUp.java:40)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=app/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{4afa871 u0a981 CEM  idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
        at android.app.ContextImpl.startService(ContextImpl.java:1484)
        at android.content.ContextWrapper.startService(ContextWrapper.java:663)
        at com.mapbox.android.telemetry.MapboxTelemetry.startLocation(MapboxTelemetry.java:491)
        at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService(MapboxTelemetry.java:227)
        at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn(MapboxTelemetry.java:198)
        at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:462)
        at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:137)
        at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:25)
        at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:10)
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit>(Telemetry.java:42)
        at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41) 
        at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46) 
        at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49) 
        at App.setMap(BuckleUp.java:71) 
        at App.onCreate(BuckleUp.java:40) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6056) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `

**Platform: Android
**Mapbox SDK version: 6.1.3

### Steps to trigger behavior

 1. Hold on the Application Icon on S8 or S8+ Probably on other phones also but thats our test phones.
Then after holding you will receive a couple options skip them and click on the icon to launch the application and you will get the crash of Telemetry.

### Expected behavior

Not to crash anymore

### Actual behavior

Crashing the app before start

**Comment by tobrun** [comment]
@electrostat @zugaldia

**Comment by ben-j69** [comment]
We also have this issue so the sdk v6 is not usable !

**Comment by jplipata** [comment]
We are seeing this crash in our crash log as well.  However I did not realize there was an update and we're on 6.1.1. 

Is 6.1.2 stable?

Here's the crash log:

Seems to be happening on Samsung Galaxy, Android 8+

```
java.lang.ExceptionInInitializerError: 
  at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000 (Telemetry.java:41)
  at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry (Telemetry.java:46)
  at com.mapbox.mapboxsdk.maps.Telemetry.initialize (Telemetry.java:30)
  at com.mapbox.mapboxsdk.Mapbox.getInstance (Mapbox.java:49)
  at com.mydomain.myapp.MyApp.onCreate (MyApp.java:86)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1125)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6056)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1764)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1538)
  at android.app.ContextImpl.startService (ContextImpl.java:1484)
  at android.content.ContextWrapper.startService (ContextWrapper.java:663)
  at com.mapbox.android.telemetry.MapboxTelemetry.startLocation (MapboxTelemetry.java:490)
  at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService (MapboxTelemetry.java:226)
  at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn (MapboxTelemetry.java:197)
  at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry (MapboxTelemetry.java:461)
  at com.mapbox.android.telemetry.MapboxTelemetry.enable (MapboxTelemetry.java:136)
  at com.mapbox.mapboxsdk.maps.Telemetry.<init> (Telemetry.java:25)
  at com.mapbox.mapboxsdk.maps.Telemetry.<init> (Telemetry.java:10)
  at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit> (Telemetry.java:42)
  at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000 (Telemetry.java:41)
  at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry (Telemetry.java:46)
  at com.mapbox.mapboxsdk.maps.Telemetry.initialize (Telemetry.java:30)
  at com.mapbox.mapboxsdk.Mapbox.getInstance (Mapbox.java:49)
  at com.mydomain.myapp.MyApp.onCreate (MyApp.java:86)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1125)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6056)
  at android.app.ActivityThread.-wrap1 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1764)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

Our config:
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.1'
implementation('com.mapbox.mapboxsdk:mapbox-android-services:2.2.10@aar') {transitive = true}
```

**Comment by jplipata** [comment]
Is 6.1.3 any improvement over 6.1.1?

My app has been getting average 5-10 crashes per hour using 6.1.1 and this is a low-usage period.

**Comment by qtdevel** [comment]
I found a workaround for that. Just add next line into `<application>` section of your Manifest.xml:

`<meta-data android:name="com.mapbox.EnableEvents" android:value="false" />`

It will disable telemetry service events, but for me it's okay. My application seems to work correctly.

**Comment by nikiizvorski** [comment]
Thanks, the workaround actually works quit well. Hope it will be supported for later versions until its fixed!

`I found a workaround for that. Just add next line into <application> section of your Manifest.xml:

<meta-data android:name="com.mapbox.EnableEvents" android:value="false" />

It will disable telemetry service events, but for me it's okay. My application seems to work correctly.`

**Comment by electrostat** [comment]
@nikiizvorski I am working through solving this issue with this PR: https://github.com/mapbox/mapbox-events-android/pull/157 It looks to be an Oreo issue you are running into by targeting Api 26+. Am I correct in that assumption? 

Either way, I'm having issues replicating the crash, so if you could pass along any additional info (how you're calling our sdk, build.gradle, specific dependencies, etc...), I'd appreciate it and work up something to test my solution against.

**Comment by LukasPaczos** [comment]
As https://github.com/mapbox/mapbox-gl-native/pull/12156 landed this one should be resolved. @nikiizvorski, @jplipata, @ben-j69, @qtdevel and anyone else impacted - would you mind retesting with `6.2.0-beta.3`? Thanks!

Closing for now as resolved, please feel free to reach out if that's not the case.

**Comment by kikin81** [comment]
We are using version 6.3.0 of the mapbox library and are experiencing this crash so it looks like it was not fixed.

**Comment by zugaldia** [comment]
@kikin81 thanks for the report - could you [cut a new ticket](https://github.com/mapbox/mapbox-gl-native/issues/new?template=android.md) and share some information that could help us reproduce the issue on our end? Thanks.
