### ISSUE TITLE
iOS: Background crash — "Failed to bind EAGLDrawable"

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-native#1243]
Five or ten minutes after locking my device (iOS 8.3, iPhone 5) but leaving Xcode attached I noticed the demo app had crashed while everything was sitting idle. On `master` 9b0376e58ee9c7b3a94b816158b41eb8dcaf2090.

```objc
2015-04-09 12:40:18.718 Mapbox GL[239:6672] [DEBUG] {0}{Map}[General]: painter setup: 245ms
2015-04-09 12:56:26.258 Mapbox GL[239:6483] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x17699380> to GL_RENDERBUFFER 1
2015-04-09 12:56:26.259 Mapbox GL[239:6483] Failed to make complete framebuffer object 8cd6
Assertion failed: (asyncRender), function triggerRender, file /mapbox-gl-native/src/mbgl/map/map.cpp, line 319.
```

**Comment by 1ec5** [comment]
Fixed in #1254.

**Comment by Sh1mor1nka** [comment]
Still get this in SDK 3.1.2, in console log

```
2016-02-25 22:10:27.453 App[19087:4463327] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x81db16f0> to GL_RENDERBUFFER 1
2016-02-25 22:10:27.453 App[19087:4463327] Failed to make complete framebuffer object 8cd6
```

I doesn't get crash, but i get blank map.
Any ideas how can i fix it? Or why i can get such behaviour?
![screen shot 2016-02-25 at 22 13 17](https://cloud.githubusercontent.com/assets/2759167/13332961/0fd24558-dc0d-11e5-84dc-e832e6034cf9.png)

**Comment by 1ec5** [comment]
@Sh1mor1nka, does the map view have a width or height of 0 points at the time you first add it to the view hierarchy? If so, you’re running into #1572.

**Comment by Sh1mor1nka** [comment]
@1ec5 Correct, firstly i add it without frame.

**Comment by Sh1mor1nka** [comment]
A'm not sure but may be it's connected...
I add pin on the map, and setCenterCoordinate right on this pin, and here is result:
![screen shot 2016-02-25 at 22 45 55](https://cloud.githubusercontent.com/assets/2759167/13333884/e6065336-dc11-11e5-9e1d-028c56841760.png)
Blue pin on top of map, not in centre.

**Comment by 1ec5** [comment]
You might consider activating Xcode’s view debugger to see if the map view is really the same size you expect it to be. From the screenshot, it looks like the upper part of the map view may be obscured.

**Comment by 1ec5** [comment]
> Works if I do ```initWithFrame``` but if I do ```[[MGLMapView alloc] init]``` and after set frame - not working.

That’s correct: if you just call `-init`, the map view is initialized with a 0×0 frame. In general, you should always provide a frame when initializing a view. Otherwise, any Auto Layout constraints you set up for that view may behave in an unexpected manner.

**Comment by Sh1mor1nka** [comment]
> You might consider activating Xcode’s view debugger to see if the map view is really the same size you expect it to be. From the screenshot, it looks like the upper part of the map view may be obscured.

size is fine

> That’s correct: if you just call -init, the map view is initialized with a 0×0 frame. In general, you should always provide a frame when initializing a view. Otherwise, any Auto Layout constraints you set up for that view may behave in an unexpected manner.

But I didn't touch this code and it works in SDK 3.0.0, it centre on pin and map wasn't blank, i just update SDK to the latest version :)

Anyway, thank you very much for your help!

**Comment by lukevella** [comment]
I was getting similar warnings in my debug console. For me the problem seemed to be caused by initializing `MGLMapView` with `CGRectZero`. I was adding constraints after adding it to my `view` but this didn't make any difference.

Initializing `MGLMapView` with a `CGRect` got rid of the warnings.

**Comment by 1ec5** [comment]
@lukevella, yes, this is a known issue: #1572.
