### ISSUE TITLE
Crash on iOS randomly after few minutes (MBGLCustomGeometrySourceOptionsFromDictionary)

### ISSUE THREAD

**Issue by sonnt1012** [mapbox/mapbox-gl-native#12533]
Recently, I've updated Mapbox sdk ver 3.7.6 to 4.1.1 and then 4.2.0. I have an issue when I run app about several minutes, the app crash very randomly. These errors can not catched by debugger, but crash reporter logged below (see attached image).
<img width="1180" alt="screen shot 2018-08-02 at 9 38 54 am" src="https://user-images.githubusercontent.com/13852761/43559533-96d8a082-9638-11e8-9906-9ddec7b218a6.png">
Any idea with this bug? Please tell me

**Comment by julianrex** [comment]
Thanks for the report @sonnt1012. Do you have any reproduction steps?

Also, are you able to test again with [`4.3.0-alpha.2`](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.3.0-alpha.2)?

**Comment by 1ec5** [comment]
This looks like a memory smasher or symbolication issue, because there’s no way Core Location would call directly or indirectly into `MBGLCustomGeometrySourceOptionsFromDictionary()`. Does this issue reproduce consistently with the same stack trace? I see that you’re using Xamarin; which package and version are you using?

**Comment by sonnt1012** [comment]
@1ec5 Yes, it happened consistently with the same stack trace. I can only log it by Appcenter crash reporter after upload symbols. I'm using binding library from Mapbox SDK iOS 4.2.0

**Comment by sonnt1012** [comment]
@julianrex Thanks for your response. It's difficult to reproduce this crash with exactly steps. It seems like a memory issue. Sometimes, I shift between tabs which one of them contains mapview then I got crash. After several minutes using app, it crashes randomly. And when I check logs in device or crash reporter, I'll get the same stack trace. And I haven't testes with  4.3.0-alpha.2 because I'm using Xamarin and I've just binding version 4.2.0.

**Comment by sonnt1012** [comment]
And an information I think it'll be useful. When I turn off LocationService, the app works without any crash.

**Comment by julianrex** [comment]
Thanks @sonnt1012 - we are actively working on a memory crasher that occurs with CLLocationManager - and suspect this to be the root cause of your issue. We expect this bug to be addressed in the upcoming `4.3.0` release.

Let's keep this issue open for the time being.

/cc @rclee

**Comment by sonnt1012** [comment]
Hi @julianrex 
No. when I only test on MapView, I've never seen crash. But I tested on iPhone 6,6s and iPhone 7 Plus. All of them currently running iOS 11.4.1 and I can only see this kind of crashes on iPhone 6 (1gb ram) and 7 Plus(3gb). I've never seen any crashes on iPhone 6s. I don't know if this information is useful with you but I think it's so strange.

Thanks in advanced,

**Comment by chrisballinger** [comment]
I am also seeing this crash in our logs, but haven't been able to reproduce.

**Comment by chrisballinger** [comment]
This is still occurring with v4.3.0-beta1

**Comment by chrisballinger** [comment]
This is by far our most prevalent crash. 

```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000002ebeb8
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x182fb4910 objc_msgSend + 16
1  Mapbox                         0x1009a4b2c MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 171244
2  Mapbox                         0x1009a4d48 MBGLCustomGeometrySourceOptionsFromDictionary(NSDictionary<NSString*, objc_object*>*) + 171784
3  CoreLocation                   0x18a5867b0 CLClientRetrieveData + 72260
4  CoreLocation                   0x18a586014 CLClientRetrieveData + 70312
5  CoreLocation                   0x18a56f9e8 CLClientInvalidate + 1240
6  CoreFoundation                 0x183d8f2bc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
7  CoreFoundation                 0x183d8ea7c __CFRunLoopDoBlocks + 264
8  CoreFoundation                 0x183d8cabc __CFRunLoopRun + 2004
9  CoreFoundation                 0x183cacda8 CFRunLoopRunSpecific + 552
10 GraphicsServices               0x185c92020 GSEventRunModal + 100
11 UIKit                          0x18dccc758 UIApplicationMain + 236
12 iBurn                          0x100573e18 main (DateFormatter+iBurn.swift:13)
13 libdyld.dylib                  0x18373dfc0 start + 4
```

**Comment by sonnt1012** [comment]
Hi Mapbox teams,
This bug still exists on Mapbox SDK 4.3.0 and I can not reproduce. Crash reporter logged the same information with previous SDK version.

Best regards,

**Comment by flashspys** [comment]
Heyho, We have the same crash here!
The App crashes randomly, even when no MapView is present. The stack trace is similar to the reporter's one
<img width="362" alt="screen shot 2018-09-10 at 11 37 07" src="https://user-images.githubusercontent.com/1114404/45293778-6d651e80-b4f9-11e8-8e4e-8c493a65b9fc.png">

Furthermore we have some symbolicated crashes from crashlytics:
<img width="890" alt="screen shot 2018-09-10 at 13 01 00" src="https://user-images.githubusercontent.com/1114404/45293842-a4d3cb00-b4f9-11e8-8f8b-346f8757b6e2.png">

For me the app crashes reproducible if I start enabling location debugging in Xcode while looking at a mapView. The crash is equal to the first one.

**Comment by JPSiller** [comment]
Hi,

I tested with Mapbox Beta 4.4 and the crash is still there. We have an app in production and we are getting tons of complaints because of this issue. For me is really easy to reproduce, open the app make sure "ShowsUserLocation is set to true". Hard close the app and open it again. It will crash constantly as long as you keep opening it. At some point it recovers. I also reported this issue in the mapbox events git:
https://github.com/mapbox/mapbox-events-ios/issues/54

Is there a workaround, anything that can stop this crash for now? If you set ShowsUserLocation = false it will stop crashing but that is not something we can do in our app. I was really excited about 4.4 because I thought it would be fixed but it is still there. 

Thanks

**Comment by JPSiller** [comment]
Hey @sonnt1012, @chrisballinger and @flashspys 

I can't still confirm this yet, but for me seems to finally work by removing the info.plist key:
MGLMapboxAccessToken and then stop using MBDirections.SharedDirections and create an object of MBDirections every time I need it, passing the same access token as the Mapbox Map.

I'm not getting the crash, and as soon as I added the MGLMapboxAccessToken key back, it starts crashing again.

Please let me know if it helps.

**Comment by julianrex** [comment]
@JPSiller are you using `MGLComputedShapeSource` at all?

**Comment by 1ec5** [comment]
> This looks like a memory smasher or symbolication issue, because there’s no way Core Location would call directly or indirectly into `MBGLCustomGeometrySourceOptionsFromDictionary()`.

The huge offset on that stack frame of https://github.com/mapbox/mapbox-gl-native/issues/12533#issuecomment-413591237 confirms that this crash has nothing to do with MGLComputedShapeSource. The function is only 25 or so Objective-C statements long. There’s no way that would balloon to 171,784 instructions and no way that the function would call itself recursively.

/ref https://github.com/mapbox/mapbox-gl-native/issues/12869#issuecomment-420879515

**Comment by 1ec5** [comment]
> I can't still confirm this yet, but for me seems to finally work by removing the info.plist key:
MGLMapboxAccessToken and then stop using MBDirections.SharedDirections and create an object of MBDirections every time I need it, passing the same access token as the Mapbox Map.

If this has any effect, it’s only because removing the access token from Info.plist prevents Mapbox Telemetry from initializing when the application launches. That would confirm that the crash is due to the events library, essentially mapbox/mapbox-events-ios#54. The application would have to provide an access token programmatically at some point before showing a Mapbox-hosted map anyways.

**Comment by flashspys** [comment]
Still have this issue in production. We found a crashlog with a different stack trace. Maybe that helps you:
![screen shot 2018-09-19 at 10 28 24](https://user-images.githubusercontent.com/1114404/45741022-e1d54700-bbf6-11e8-99ed-1dac59eecad6.png)

**Comment by julianrex** [comment]
@flashspys what versions of the Maps (and Navigation if relevant) SDKs are you building with?

**Comment by flashspys** [comment]
@julianrex We used the following pods. But we just rolling out 4.4.1 to our testers.
```
  pod 'Mapbox-iOS-SDK', '~> 4.3'
  pod 'MapboxDirections.swift', '~> 0.22'
  pod 'MapboxNavigation', '~> 0.20'
```

**Comment by julianrex** [comment]
Thanks @flashspys - we believe that the crash has been addressed by the `4.4.1` patch release, so please let us know if you continue to see related crash reports.

**Comment by parrots** [comment]
I'm still seeing this in production (similar stack trace to @flashspys), using SDK 4.5.0. It is currently my top crasher for my app :/. I am not showing the current user location on the map, FWIW.

<img width="1078" alt="screen shot 2018-11-06 at 3 21 08 pm" src="https://user-images.githubusercontent.com/171163/48091474-cab6dc80-e1d7-11e8-87cf-878bf16e3690.png">

**Comment by julianrex** [comment]
@parrots are you still seeing this? (Have you upgraded?)

**Comment by flashspys** [comment]
We're running SDK version 4.7.1 and not seeing this crash on Crashlytics anymore.

**Comment by julianrex** [comment]
Thanks @flashspys. I'm going to close this issue,  but all - please reopen if you see it again!

**Comment by parrots** [comment]
I have not seen this on the latest versions. 👍

**Comment by JGregoryAtiba** [comment]
I'm seeing very similar crashes in a Xamarin Forms iOS app, and trying to track the bug down.  To be clear, we're not using MapBox, but we have the same stack trace that goes through `CLClientStopVehicleHeadingUpdates` and then bounces to somewhere else which is almost certainly unrelated.

@julianrex could you possibly point to a commit or PR between v4.5.0 and v4.7.1 that you believe fixed this issue for MapBox?  Or any other insights?  Many thanks!

**Comment by mohammedDehairy** [comment]
> I'm seeing very similar crashes in a Xamarin Forms iOS app, and trying to track the bug down. To be clear, we're not using MapBox, but we have the same stack trace that goes through `CLClientStopVehicleHeadingUpdates` and then bounces to somewhere else which is almost certainly unrelated.
> 
> @julianrex could you possibly point to a commit or PR between v4.5.0 and v4.7.1 that you believe fixed this issue for MapBox? Or any other insights? Many thanks!

We have the same problem, any one care to share the fix for this crash? 

```
0   App                   XXXX + 4381246348
1   CoreLocation    CLClientStopVehicleHeadingUpdates + 72552
2   CoreLocation    CLClientStopVehicleHeadingUpdates + 70504
3   CoreLocation    CLClientInvalidate + 1288
```

**Comment by JGregoryAtiba** [comment]
@mohammedDehairy Sorry, I don't believe we ever found the solution to this.  The app was passed on from my team to another team, and I don't know if they continued to see this error or not.  I think your best bet is to make sure you're building against the latest versions of Xamarin or Xcode or whatever you're using...  Wish I could have been more helpful!
