### ISSUE TITLE
Android - OfflineManager callbacks not being called from mapbox

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native#13473]
I am trying to download a region as big as half of the state of Victoria (Australia). When I try deleting the offline region (which is being downloaded), callbacks provided by the offline manager are not being called by mapbox. In this case the callback for OfflineManager.listOfflineRegions is never called (not onList or onError). For the download I am using an IntentService running as a foreground service. This issue is not appearing if the offline region is much smaller. We are still working on determine how big the region needs to be to cause this problem.

### Steps to reproduce

 1. Define your region as big as half of the state of Victoria (Australia). Define minZoom of 2 and maxZoom of 15. (if needed I can provide a style url but I would prefer to provide this information via email).
 2. Download this region.
 3. Try to delete this region while is being downloaded via the offline manager.

### Expected behavior
Callbacks by the offline manager are being called.

### Actual behavior
Callbacks by the offline manager are not being called.

### Configuration

**Android versions:** all
**Mapbox SDK versions:** 6.7.1

**Comment by Mordag** [comment]
**Update:** We were able to find the possible threshold for the offline region download. When using minZoom of 2 and maxZoom of 15, the threshold until when the offline download is working is 6.068401365244313E10 ㎡.

**Comment by tobrun** [comment]
@Mordag thank you for the report. Could you add some context/code how you are `deleting region while it being downloaded`. Afaik you need to set the download to inactive before deleting it:

```java
      offlineRegion.setDownloadState(OfflineRegion.STATE_INACTIVE);
      offlineRegion.setObserver(null);
      offlineRegion.delete(new OfflineRegion.OfflineRegionDeleteCallback() {
        @Override
        public void onDelete() {
          // no-op
        }

        @Override
        public void onError(String error) {
          // no-op
        }
      });
```

In words, you need to stop the download before deleting the region

**Comment by LukasPaczos** [comment]
Hey @Mordag, we've recently discovered a thread deadlock in our offline manager, which is fixed in the `v7.2.0`. Would you mind retesting with that version? I'm not sure if the issue you're seeing is connected to the deadlock, but we'd appreciate if you could verify that before we dive deeper. Thank you!

**Comment by Mordag** [comment]
@LukasPaczos Sure I will take a look in the next days if I can still reproduce that issue.

**Comment by Mordag** [comment]
@LukasPaczos The deadlock seems to be resolved. But I still have issues after reaching the max tile count. When reaching that state and trying to remove an offline region, I am unable to download a new offline region. Is that issue related to the bugfix?

**Comment by LukasPaczos** [comment]
> The deadlock seems to be resolved.

Awesome, thank you for verifying.

> When reaching that state and trying to remove an offline region, I am unable to download a new offline region.

Is this happening on `v7.2.0`? Would you mind cutting a new ticket? Thanks again!

**Comment by Mordag** [comment]
@LukasPaczos I already opened https://github.com/mapbox/mapbox-gl-native/issues/13437 for that problem. That is still happening with 7.2.0.
