### ISSUE TITLE
[iOS] setVisibleCoordinateBounds acts randomly

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#14991]
On iOS SDK 5.1, I'm using the method

- (void)setVisibleCoordinateBounds:(MGLCoordinateBounds)bounds animated:(BOOL)animated;

to center the view on a region. Each time I call this, the camera animation does not end on the region fitting the view as it used to on SDK 4.9 and 5.0. See linked video.
[SetVisibleBounds.mp4.zip](https://github.com/mapbox/mapbox-gl-native/files/3320990/SetVisibleBounds.mp4.zip)

### Steps to reproduce

 1. Create a region
 2. Move the map by hand
 3. Ask the map to center on the region

### Expected behavior
The map shows the region fit in the view.

### Actual behavior
The map show the regions with some offset, animation seems not to end correctly

### Configuration

**Mapbox SDK versions: 5.1** 
**iOS/macOS versions: 12** 
**Device/simulator models: both**
**Xcode version:10.2**

**Comment by RomainQuidet** [comment]
I have the same strange behavior with method
- (void)showAnnotations:(NSArray<id <MGLAnnotation>> *)annotations edgePadding:(UIEdgeInsets)insets animated:(BOOL)animated;

**Comment by RomainQuidet** [comment]
@1ec5 it seems to me that region animation fail du to performance issue in MGLMapView.mm where `setNeedsRerender`is called too many times, (CPU usage up to 80% without moving the map), creating new camera and then creating an animation collision.

**Comment by RomainQuidet** [comment]
Just start the demo app, tap on center user button, the map zoom in on the user. From here the CPU never goes down (50 to 90%) and the app creates in loop camera from the rendering...

**Comment by RomainQuidet** [comment]
<img width="1666" alt="Capture d’écran 2019-06-24 à 16 46 54" src="https://user-images.githubusercontent.com/8179069/60028513-bad50580-969f-11e9-9b8e-02a6b173ddb2.png">

**Comment by julianrex** [comment]
Thanks for the amazing feedback @RomainQuidet!

**Comment by m-stephen** [comment]
@RomainQuidet I believe this issue has been fixed by #15130. You can try it and thanks again for your feedback!

**Comment by RomainQuidet** [comment]
Thanks for the correction, I'll try SDK 5.2 beta as soon as possible!

**Comment by RomainQuidet** [comment]
Hi, I did a 5.2 update on our app, the behavior is not anymore random, but still incorrect (systematic wrong offset computed)...
