### ISSUE TITLE
3D Buildings, point on map below building 

### ISSUE THREAD

**Issue by onzio88r** [mapbox/mapbox-gl-native#15148]
### Steps to reproduce

 1. Enable 3D building 
 2. Add points on map with custom image annotation
 3. The point appear below the building

### Expected behavior

3D building and point on map

### Actual behavior

Every layer, point, traffic, roads name 
are below the buildings, the points on map are not visible

### Configuration

**Mapbox SDK versions:**  Latest version
**iOS/macOS versions:**  iOS 12
**Device/simulator models:** Problem in real device and simulator 
**Xcode version:**  10

**Comment by LukasPaczos** [comment]
Thanks for reaching out @onzio88r, this has been fixed in https://github.com/mapbox/mapbox-gl-native/pull/15065.

**Comment by onzio88r** [comment]
Hi, i got the last mapbox sdk and the problem still there
There is a specufic procedure to get this fix? 
I used pod repo update and po install

**Comment by LukasPaczos** [comment]
The fix has not been released yet @onzio88r, it's going to be a part of `5.2.0`.

**Comment by onzio88r** [comment]
Many thanks for the information


Il giorno mar 23 lug 2019 alle ore 10:45 Łukasz Paczos <
notifications@github.com> ha scritto:
