### ISSUE TITLE
Random crash during offline download

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-native#15482]
I have a random crash at the end of multiple parallel offline map download (my app download 10 maps in parallel). I know it is not easy to reproduce but I wonder if it sounds familiar to you.
Here is the tombstone. Could someone please tell me which function in Mapbox the crash comes from?
I will look in my code what trigger the call.

```
2019-08-26 09:53:50.811 24560-26682/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 26682 (DefaultFileSour)
2019-08-26 09:53:50.830 575-972/? E/qti_sensors_hal: [SSC_HAL] ACCEL, X:0.06 Y:8.32 Z:5.25
2019-08-26 09:53:50.848 24560-27249/? V/Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
2019-08-26 09:53:51.014 7982-7982/? I/crash_dump64: obtaining output fd from tombstoned
2019-08-26 09:53:51.020 2184-2184/? I//system/bin/tombstoned: received crash request for pid 24560
2019-08-26 09:53:51.023 7982-7982/? I/crash_dump64: performing dump of process 24560 (target tid = 26682)
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: Build fingerprint: 'asus/WW_Phone/ASUS_Z012D:8.0.0/OPR1.170623.026/15.0410.1807.75-0:user/release-keys'
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: Revision: '0'
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: ABI: 'arm64'
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: pid: 24560, tid: 26682, name: DefaultFileSour  >>> com.warfog.wizar.adventure.map.local <<<
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
2019-08-26 09:53:51.023 7982-7982/? A/DEBUG: Cause: null pointer dereference
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x0   0000000000000000  x1   000311cdad160000  x2   0000000000000000  x3   000000729f9c3f10
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x4   000000729cb11324  x5   000000729ac98364  x6   00000072c2859000  x7   000000000b902532
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x8   000000729ff0ac38  x9   000000005d70bf0e  x10  00000000000f4240  x11  0d17d9affd03e7c2
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x12  0000000000000018  x13  000000005d63900e  x14  002e4ec86a2890ac  x15  0000446d4b14e539
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x16  000000729ff11720  x17  00000072c10a8204  x18  00000000000001bb  x19  0000000000000000
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x20  000000729f9c3f10  x21  000000729f9c4588  x22  000000003b9aca00  x23  7fffffffffffffff
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x24  000000000000000e  x25  00073f289d29dad6  x26  000000729ca2ece0  x27  000000729f9c42a8
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     x28  00000072a3ed4560  x29  000000729f9c3f00  x30  000000729fd6cb8c
2019-08-26 09:53:51.024 7982-7982/? A/DEBUG:     sp   000000729f9c3ee0  pc   000000729fb4a7e4  pstate 0000000080000000
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG: backtrace:
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #00 pc 00000000000887e4  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #01 pc 00000000002aab88  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #02 pc 00000000002ab6fc  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #03 pc 00000000002abbc0  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #04 pc 000000000028a27c  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #05 pc 0000000000057d2c  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #06 pc 00000000000571b0  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #07 pc 0000000000294fb0  /data/app/com.warfog.wizar.adventure.map.local-sQwLQftaF5JUHG-QJ5gMsQ==/lib/arm64/libmapbox-gl.so
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #08 pc 00000000000666a0  /system/lib64/libc.so (_ZL15__pthread_startPv+36)
2019-08-26 09:53:51.031 7982-7982/? A/DEBUG:     #09 pc 000000000001f1a4  /system/lib64/libc.so (__start_thread+68)
```
### Configuration

**Android versions:** 
8.0.0
**Device models:** 
Asus Zenphone Laser 3
**Mapbox SDK versions:**
v8:0.7.0

### Code source

My app use a cordova plugin on my own but, [here is the Mapbox java code.](https://github.com/dagatsoin/cordova-plugin-mapbox/tree/master/src/android)

**Comment by alexshalamov** [comment]
@dagatsoin thank you for report. Issue you reported may be a side-effect of a https://github.com/mapbox/mapbox-gl-native/issues/14740 bug that was fixed in https://github.com/mapbox/mapbox-gl-native/pull/15330

**Comment by dagatsoin** [comment]
@alexshalamov Interesting, thx, I will try to update the dependencies and retry. Could you leave it open for now? I will be back after few tests.

**Comment by dagatsoin** [comment]
I use the last snapshot of the annotation plugin and still have this error.

```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.8.0-SNAPSHOT'
```

Last tombstone:

```
08-26 19:25:44.048 13905 13905 I crash_dump64: obtaining output fd from tombstoned
08-26 19:25:44.049  2184  2184 I /system/bin/tombstoned: received crash request for pid 8711
08-26 19:25:44.050 13905 13905 I crash_dump64: performing dump of process 8711 (target tid = 9837)
08-26 19:25:44.051 13905 13905 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-26 19:25:44.051 13905 13905 F DEBUG   : Build fingerprint: 'asus/WW_Phone/ASUS_Z012D:8.0.0/OPR1.170623.026/15.0410.1807.75-0:user/release-keys'
08-26 19:25:44.051 13905 13905 F DEBUG   : Revision: '0'
08-26 19:25:44.052 13905 13905 F DEBUG   : ABI: 'arm64'
08-26 19:25:44.052 13905 13905 F DEBUG   : pid: 8711, tid: 9837, name: DefaultFileSour  >>> com.warfog.wizar.adventure.map.local <<<
08-26 19:25:44.052 13905 13905 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7200000010
08-26 19:25:44.052 13905 13905 F DEBUG   :     x0   000000729c919b80  x1   00000072a52b1688  x2   0000000000000020  x3   00000072a52b16a8
08-26 19:25:44.052 13905 13905 F DEBUG   :     x4   00000072a52b16a8  x5   00000072a52b16c8  x6   000000729c5c8bf0  x7   000000729debe8a0
08-26 19:25:44.052 13905 13905 F DEBUG   :     x8   0000007200000000  x9   0d17d9affd03e7c2  x10  0000000000000000  x11  0000000000000000
08-26 19:25:44.052 13905 13905 F DEBUG   :     x12  0000007299f91700  x13  000000729c5c8bc0  x14  00000000ffffffff  x15  00000000000e8f40
08-26 19:25:44.052 13905 13905 F DEBUG   :     x16  00000072c1154518  x17  00000072c10a8a00  x18  0000000013654508  x19  000000729c8383e0
08-26 19:25:44.052 13905 13905 F DEBUG   :     x20  00075e4b923801c8  x21  000000729797dca0  x22  000000729ccfb298  x23  000000729c838430
08-26 19:25:44.052 13905 13905 F DEBUG   :     x24  000000729ccfb588  x25  00075ec28b7feb51  x26  000000729c838430  x27  000000729ccfb298
08-26 19:25:44.052 13905 13905 F DEBUG   :     x28  000000729f7929d0  x29  000000729ccfb310  x30  000000729f8ed220
08-26 19:25:44.052 13905 13905 F DEBUG   :     sp   000000729ccfb290  pc   000000729f8ed218  pstate 0000000020000000
08-26 19:25:44.065 13905 13905 F DEBUG   : 
08-26 19:25:44.065 13905 13905 F DEBUG   : backtrace:
08-26 19:25:44.065 13905 13905 F DEBUG   :     #00 pc 0000000000059218  /data/app/com.warfog.wizar.adventure.map.local-k0KO-dNq6U969mhgZV2YTA==/lib/arm64/libmapbox-gl.so
08-26 19:25:44.065 13905 13905 F DEBUG   :     #01 pc 000000000005871c  /data/app/com.warfog.wizar.adventure.map.local-k0KO-dNq6U969mhgZV2YTA==/lib/arm64/libmapbox-gl.so
08-26 19:25:44.065 13905 13905 F DEBUG   :     #02 pc 000000000029f7d8  /data/app/com.warfog.wizar.adventure.map.local-k0KO-dNq6U969mhgZV2YTA==/lib/arm64/libmapbox-gl.so
08-26 19:25:44.065 13905 13905 F DEBUG   :     #03 pc 00000000000666a0  /system/lib64/libc.so (_ZL15__pthread_startPv+36)
08-26 19:25:44.065 13905 13905 F DEBUG   :     #04 pc 000000000001f1a4  /system/lib64/libc.so (__start_thread+68)
```

Here is few lines of log before the crash.
Note this line just before the fatal signal. Does it sound familiar to you?
```
08-26 19:25:43.825  8711 10224 I Mbgl-HttpRequest: Request failed due to a connection error: SSL handshake aborted: ssl=0x7296599c40: I/O error during system call, Bad file descriptor 
```

```
08-26 19:25:42.079  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.104  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.106  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.107  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.113  8711  8724 I zygote64: Background concurrent copying GC freed 196508(10MB) AllocSpace objects, 32(3MB) LOS objects, 58% free, 8MB/20MB, paused 551us total 102.451ms
08-26 19:25:42.133  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.145  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.153  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.155  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.162  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.168  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.168  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.175  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.181  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.184  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.194  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.207  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.207  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.217  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.235  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.241  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.248  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.248  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.249  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.254  2434 31210 I GnssLocationProvider: [GPS][CB] SV count: 36 ephemeris count: 0 almanac count: 31 CNo_Ovr25: 5 CNo_Ovr30: 5 CNo_Ovr35: 0
08-26 19:25:42.262  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.262  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.271   575   972 E qti_sensors_hal: [SSC_HAL] ACCEL, X:0.05 Y:8.27 Z:5.25
08-26 19:25:42.281  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.287  8711  8711 D MAP_CONTROLLER: 1033/1037 resources; 64805529 bytes downloaded.
08-26 19:25:42.295  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.296  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.303  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.308  8711  8711 D MAP_CONTROLLER: 1034/1037 resources; 64858491 bytes downloaded.
08-26 19:25:42.330  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.333  8711  8711 D MAP_CONTROLLER: 1035/1037 resources; 64952136 bytes downloaded.
08-26 19:25:42.347  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.347  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.348  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.349  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.351  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.354  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.411  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.416  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.417  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.423  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.423  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.424  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.425  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.427  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.447  8711  8711 D MAP_CONTROLLER: 1033/1037 resources; 63707169 bytes downloaded.
08-26 19:25:42.463  8711  8711 D MAP_CONTROLLER: 1034/1037 resources; 63760131 bytes downloaded.
08-26 19:25:42.473  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.474  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.474  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.476  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.478  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.480  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.481  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.483  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.489  8711  8711 D MAP_CONTROLLER: 1035/1037 resources; 63853776 bytes downloaded.
08-26 19:25:42.507  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.534  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.538  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.543  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.545  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.550  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.551  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.571  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.571  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.573  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.585  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.585  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.591  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.619  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.632  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.642  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.662  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.664  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.665  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.666  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.668  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.669  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.669  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.678  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.681  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.703  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.704  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.706  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.710  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.729  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.731  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.734  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.738  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.738  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.740  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.740  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.742  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.749  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.750  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.760  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.775  8711  8711 D MAP_CONTROLLER: 1033/1041 resources; 62635224 bytes downloaded.
08-26 19:25:42.791  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.795  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.795  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.798  8711  8711 D MAP_CONTROLLER: 1034/1041 resources; 62688186 bytes downloaded.
08-26 19:25:42.800  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.800  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.800  2434  2833 D WifiStateMachine:  ConnectedState !CMD_RSSI_POLL rt=2074002600/3989104007 394 0 "iPhone de vikti" 3e:91:48:a6:b2:2b rssi=-44 f=2437 sc=60 link=72 tx=1328,5, 0,0, 0,0  rx=1649,8 bcn=0 [on:0 tx:0 rx:0 period:3006] from screen [on:0 period:-1024995473] score=60
08-26 19:25:42.801  2434  2833 D WifiStateMachine:  L2ConnectedState !CMD_RSSI_POLL rt=2074002601/3989104008 394 0 "iPhone de vikti" 3e:91:48:a6:b2:2b rssi=-44 f=2437 sc=60 link=72 tx=1328,5, 0,0, 0,0  rx=1649,8 bcn=0 [on:0 tx:0 rx:0 period:1] from screen [on:0 period:-1024995472] score=60
08-26 19:25:42.806  2434  2833 D WifiStateMachine: [wlan]: ["iPhone de vikti", 3e:91:48:a6:b2:2b]=(-44, 72)
08-26 19:25:42.819  8711  8711 D MAP_CONTROLLER: 1035/1041 resources; 62781831 bytes downloaded.
08-26 19:25:42.890  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.893  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.898  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.909  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.909  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.921  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.923  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.933  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.934  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.941  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.951  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.959  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.967  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.974  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:42.978  8711  8711 D MAP_CONTROLLER: 969/1041 resources; 59026634 bytes downloaded.
08-26 19:25:42.996  8711  8711 D MAP_CONTROLLER: 970/1041 resources; 59079596 bytes downloaded.
08-26 19:25:43.004  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.006  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.006  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.006  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.008  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.009  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.009  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.010  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.011  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.030  8711  8711 D MAP_CONTROLLER: 971/1041 resources; 59173241 bytes downloaded.
08-26 19:25:43.039  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.107  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.111  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.111  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.113  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.114  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.116  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.118  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.119  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.154  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.154  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.155  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.169  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.173  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.175  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.177  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.177  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.178  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.179  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.181  8711  8711 D MAP_CONTROLLER: 969/1045 resources; 58453192 bytes downloaded.
08-26 19:25:43.194  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.197  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.197  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.208  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.209  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.212  8711  8711 D MAP_CONTROLLER: 970/1045 resources; 58506154 bytes downloaded.
08-26 19:25:43.217  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.220  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.231  8711  8711 D MAP_CONTROLLER: 971/1045 resources; 58599799 bytes downloaded.
08-26 19:25:43.253  2434 31210 I GnssLocationProvider: [GPS][CB] SV count: 36 ephemeris count: 0 almanac count: 31 CNo_Ovr25: 5 CNo_Ovr30: 5 CNo_Ovr35: 0
08-26 19:25:43.267  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.281   575   972 E qti_sensors_hal: [SSC_HAL] ACCEL, X:0.03 Y:8.30 Z:5.21
08-26 19:25:43.283  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.290  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.303  8711 10223 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.303  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.306  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.308  8711 10225 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.310  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.312  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.325  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.334  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.350  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.352  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.354  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.378  8711  8711 D MAP_CONTROLLER: 969/1037 resources; 59011499 bytes downloaded.
08-26 19:25:43.390  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.402  8711  8711 D MAP_CONTROLLER: 970/1037 resources; 59064461 bytes downloaded.
08-26 19:25:43.404  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.405  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.405  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.405  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.406  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.406  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.409  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.424  8711  8711 D MAP_CONTROLLER: 971/1037 resources; 59158106 bytes downloaded.
08-26 19:25:43.426  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.436  8711 10231 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.439  8711 10841 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.455  8711  8711 D MAP_CONTROLLER: 1033/1037 resources; 62242992 bytes downloaded.
08-26 19:25:43.466  8711 10842 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.469  8711 10226 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.471  8711 10216 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.476  8711  8711 D MAP_CONTROLLER: 1034/1037 resources; 62295954 bytes downloaded.
08-26 19:25:43.479  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.487  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.491  8711 10227 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.492  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.494  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.495  8711  8711 D MAP_CONTROLLER: 1035/1037 resources; 62389599 bytes downloaded.
08-26 19:25:43.512  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.528  8711 10224 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.532  8711 10238 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.551  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.620  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.634  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.634  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.640  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.654  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.690  8711  8711 D MAP_CONTROLLER: 1075/1037 resources; 65654516 bytes downloaded.
08-26 19:25:43.694  8711  8711 D MAP_CONTROLLER: 1075/1037 resources; 65654516 bytes downloaded.
08-26 19:25:43.729  8711 10840 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.730  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.735  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.738  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.749  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.812  8711  8711 D MAP_CONTROLLER: 1057/1037 resources; 64187626 bytes downloaded.
08-26 19:25:43.818  8711  8711 D MAP_CONTROLLER: 1057/1037 resources; 64187626 bytes downloaded.
08-26 19:25:43.820  8711 10238 I Mbgl-HttpRequest: Request failed due to a connection error: Socket closed 
08-26 19:25:43.822  8711 10217 I Mbgl-HttpRequest: Request failed due to a connection error: Socket is closed 
08-26 19:25:43.825  8711 10224 I Mbgl-HttpRequest: Request failed due to a connection error: SSL handshake aborted: ssl=0x7296599c40: I/O error during system call, Bad file descriptor 
08-26 19:25:43.828  8711  9837 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7200000010 in tid 9837 (DefaultFileSour)
08-26 19:25:43.865  8711 10214 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.870  8711 10217 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.873  8711 10230 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.874  8711 10272 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.904  8711 10242 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.907  8711 10234 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.910  8711 10233 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.914  8711 12581 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
08-26 19:25:43.934  8711 12582 V Mbgl-HttpRequest: [HTTP] Request was successful (code = 200).
```
