### ISSUE TITLE
Missing icons on Qt 5.15

### ISSUE THREAD

**Issue by afendin** [mapbox/mapbox-gl-native#16545]
Until now I had used `mapbox://styles/mapbox/navigation-preview-night-v2` style, which was working fine. But when I changed my style no "Navigation"(which is default template from Mapbox Studio), I got following warnings:

```
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [1]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{QSGRenderThread}[ParseStyle]: [1]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."

```

And my map does not have half of icons on it.
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/OBcR7.png

Here's my code sample:
```
import QtQuick 2.15
import QtQuick.Window 2.15
import QtLocation 5.15
import QtPositioning 5.15

Window {
    width: 640
    height: 480
    visible: true
    title: qsTr("Hello World")

    Map {
        anchors.fill: parent

        zoomLevel: 15
        plugin: Plugin {
            name: "mapboxgl"

            PluginParameter {
                name: "mapboxgl.access_token"
                value: "pk.eyJ1IjoiYW1pcmFmZW5kaW4iLCJhIjoiY2p3dWpxa2c0MGs4aTN5cXpnbGx0Z2liaiJ9.bhSGga4rMM44DhZ-JKigfg"
            }

            PluginParameter {
                name: "mapboxgl.mapping.additional_style_urls"
                value: "mapbox://styles/amirafendin/ckg9ac41f04pn19o9m7chp63o"
            }
        }

        activeMapType: supportedMapTypes[0]
    }
}

```

**Comment by afendin** [comment]
To make it work had to replace 

```
["get", "filterrank"]
["get", "sizerank"]
["get", "symbolrank"]
["get", "len"]
["get", "reflen"]
["get", "layer"]

```
in filters with

```
["to-number", ["get", "filterrank"]]
etc...
```

**Comment by M-Kerr** [comment]
I have the ParseStyle issue as well after using a custom navigation map url.

**Comment by j-mar** [comment]
Number conversion appears to have broken with Qt 5.15. I've implemented a fix here:
https://github.com/mapbox/mapbox-gl-native/pull/16562

**Comment by AndyShawQt** [comment]
I am also seeing this, but the suggested fix does not seem to be helping in this case, the errors:
```

[ WARNING ]  "{unknown}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [3]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [2]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [1]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
[ WARNING ]  "{unknown}[ParseStyle]: [1]: Expected arguments of type (number, number) | (string, string), but found (value, number) instead."
```

still appear with it in place.

**Comment by K1ngjulien** [comment]
any update on this? I'm using a custom style url on Qt 5.15.2 and still get the same "ParseStyle" errors. Is this fixed in any newer releases?

**Comment by akontsevich** [comment]
I have same warnings.

**Comment by zimml** [comment]
Same issue for me.
