### ISSUE TITLE
investigate compatibility with CocoaPods 0.38.0 betas

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-native#1849]
See https://github.com/mapbox/mapbox-gl-native/issues/1847 for an example. 

https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md

Seems to be a fair amount of linker-related changes, including https://github.com/CocoaPods/CocoaPods/issues/3537.

**Comment by friedbunny** [comment]
Per https://github.com/mapbox/mapbox-gl-native/issues/1862#issuecomment-120007533, it appears that `-ObjC` isn't being added to the "Pods" target's linker flags when using ~0.38.0.

**Comment by 1ec5** [comment]
Yes, that’s fallout from CocoaPods/CocoaPods#3537.

**Comment by 1ec5** [comment]
A fix is ready in #1876, but we may not be able to publish the updated spec to CocoaPods for possibly another week. In the meantime, anyone on CocoaPods 0.38.0 should use this in their Podfile as a temporary workaround:

```ruby
pod 'MapboxGL', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/1ec5-pod-038-1849/ios/MapboxGL.podspec'
use_frameworks!
```

**Comment by kylederkacz** [comment]
https://raw.githubusercontent.com/mapbox/mapbox-gl-native/1ec5-pod-038-1849/ios/MapboxGL.podspec is 404'ing. Is there a new podspec somewhere? (I tried the podspec from the master branch, but am still seeing this error)

**Comment by 1ec5** [comment]
@kylederkacz, sorry, I should’ve updated this ticket. The issue has been fixed, so you can use the official podspec without a URL, [as described here](https://www.mapbox.com/mapbox-gl-ios/#cocoapods).

**Comment by 1ec5** [comment]
Although the version in master should be fine, too. Can you check whether you have `-ObjC` set according to [this comment](https://github.com/mapbox/mapbox-gl-native/issues/1862#issuecomment-120007533)? Thanks.

**Comment by kylederkacz** [comment]
I added the linker flags and but it's still not working. Any ideas? (I'm pretty new to iOS dev)

Podfile:
```
platform :ios, "8.0"

target "App" do
  ...
  pod 'MapboxGL'
  ...
end
```

```
$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
...
Installing MapboxGL (0.5.1)
...
Generating Pods project
Integrating client project
Sending stats
```

![screen shot 2015-08-06 at 7 32 15 pm](https://cloud.githubusercontent.com/assets/1800391/9128373/579e2c02-3c7c-11e5-84e0-17456731b969.png)

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MGLMapView", referenced from:
      __TMaCSo10MGLMapView in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 1ec5** [comment]
@kylederkacz, which versions of Xcode and the iOS SDK are you building with? Is `ViewController` written in Swift or Objective-C?

**Comment by kylederkacz** [comment]
Xcode: Version 6.4 (6E35b)
iOS SDK: 8.4
ViewController: Swift

**Comment by kylederkacz** [comment]
I've deleted the Pods dir and `pod cache clean --all` ... still no dice

**Comment by 1ec5** [comment]
Can you try going to Product ‣ Clean Build Folder (hold down option) and rebuilding?

**Comment by kylederkacz** [comment]
Cleaning the build folder didn't seem to fix the problem, but I started going through the other dependencies that I had in my Podfile, disabling them one at a time, and, after I disabled FXBlurView, everything was peachy again. Sorry for the wild goose chase.

**Comment by 460122775** [comment]
How to solve this problem? I tried almost all solutions, but no use.
After I upgrade to the iOS 9.3, then I get the error : 
"_OBJC_CLASS_$_MGLMapView",referenced from:
      type metadata accessor for __ObjC.MGLMapView in ProductViewA.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
==================================
I feel sleepy to this Mapbox-iOS-SDK, I delete it from cocoapods, download the sdk, and reset it by manual  step by step with the README.md , but....no use!
I fall in love with this map`s appearance, but Why it is so difficult to use this sdk?

**Comment by 1ec5** [comment]
Hi @460122775, it’s possible that the issue you’re seeing is unrelated to the other issues described here, which were fixed long ago. A few questions for you, so we can better understand what’s going on:

1. Is your project written in Objective-C or Swift?
1. Is Bitcode enabled? (It should be enabled by default if you’re using a recent Xcode version.)
1. When you installed the SDK manually, did you install the dynamic framework or the static framework?
1. If you installed the static framework, did you add `-ObjC` to the `OTHER_LDFLAGS` build setting?
1. Does the error persist after cleaning your derived data (hold down Option and go to Product ‣ Clean Build Folder)?
