### ISSUE TITLE
Black screen, not show the map

### ISSUE THREAD

**Issue by LuisBotero** [mapbox/mapbox-gl-native#2802]
When I try to open the map, the screen goes black, and never the map is displayed.
I tried doing a new application in Android Studio and I downloaded the demo of the Play Store, I have the same problem in both applications.
I'm working on Android version 4.2.2.

![screenshot_2015-10-26-11-56-06](https://cloud.githubusercontent.com/assets/12969249/10736214/c8af9ff6-7bd9-11e5-8ccb-92c8797c1173.png)

**Comment by tobrun** [comment]
Could you add the code where you are Initializing the map? 
Can you verify if you are calling the different lifecycle methods?
 
Linking issue (#2513) with same problem.
@bleege @ljbade @zugaldia

**Comment by LuisBotero** [comment]
The code are calling the different lifecycle methods correctly, onCreate, onStart, onResume, etc
There are some screenshots of my code, the activity_main and MainActivity classes, and also attached some results in the Logcat console when I open my application. The code used is like the example of the documentacion in the website of MapBox Android API.

![mainactivity](https://cloud.githubusercontent.com/assets/12969249/10739605/68fb3086-7beb-11e5-9b42-c25806c5a16f.png)
![activity_main](https://cloud.githubusercontent.com/assets/12969249/10739606/68fd82b4-7beb-11e5-88a2-1be668a6764e.png)
![logcat](https://cloud.githubusercontent.com/assets/12969249/10739604/68f9a8d8-7beb-11e5-8cc6-b4f0e2283ff5.png)

**Comment by tobrun** [comment]
@LuisBotero this is great info to have, thank you for that!

**Comment by ljbade** [comment]
@LuisBotero Can you try https://github.com/mapbox/mapbox-gl-native/pull/2810 to see if it fixes this issue?

**Comment by LuisBotero** [comment]
@ljbade I'm still having the same problem, the map is not displayed, I tried with versions 2.1.0 and 2.2.0 of MapBox and none have worked for me.
I need to do something extra in my code?

**Comment by tobrun** [comment]
@LuisBotero: 
@ljbade indicated building from source. A new SNAPSHOT, that you can use as a gradle dependency, will be released later today. Would be awesome if you could test again with that. Will ping you if that SNAPSHOT lands.

**Comment by bleege** [comment]
@LuisBotero We just released a new SNAPSHOT from our testing in #2817.  Please feel free to give it a shot to make sure we were able to solve the problem.  Instructions on how to install it are available at https://www.mapbox.com/android-sdk/#gradle.

Thanks again for reporting this issue and for using the SDK!

**Comment by LuisBotero** [comment]
@bleege I'm still having trouble running my code. The map still shows black screen on my phone and the AVD stops working when I run my application with the map.

This is my build.gradle
![buildg](https://cloud.githubusercontent.com/assets/12969249/10772682/4918e3dc-7cc5-11e5-9e7d-2a2412cf2517.png)

This is what I get in my xml
![xml](https://cloud.githubusercontent.com/assets/12969249/10772773/a44e3a90-7cc5-11e5-92ea-7591a6e55c39.png)

And this is my class.
![class](https://cloud.githubusercontent.com/assets/12969249/10772856/1af8c610-7cc6-11e5-9df6-92bd886a6695.png)

Am i doing something wrong?. Why my map does not work?
I'm working with Android 4.2.2 in the AVD and on my phone.
Thank you for your help!!

**Comment by tobrun** [comment]
@LuisBotero 

Thank you for sharing your code,
I have created a separate project to test this in, 
I copied your code and loaded it up on a nexus 5 emulator running 4.2.2:

![screen shot 2015-10-27 at 23 44 59](https://cloud.githubusercontent.com/assets/2151639/10774992/3e0a5f3a-7d05-11e5-813b-20fd4241a0d0.png)

It seems that your Gradle is not using the newer version of the SNAPSHOT but rather a cached one. The results you are describing are the same as before the fix of @ljbade for 4.x devices . 

Could you try doing a `sync gradle with project files`?
Do you see anything in the logging while running?

**Comment by ljbade** [comment]
@LuisBotero I created an issue for the layout editor bug in https://github.com/mapbox/mapbox-gl-native/issues/2830

What happens if you move `mapView.onCreate()` above the `mapView.set...` lines?

**Comment by bleege** [comment]
@LuisBotero Thanks for testing it out.  A couple of things to try:

1. Swap the line order of `mavenCentral()` and `maven { url: ""}`
1. Try is to do a force update of the Gradle dependency in the command line while Android Studio is closed and then reopen it so that Android Studio picks up all the changes.  I know that's kinda lame, but I've noticed this before.

To force dependency updates:

```sh
cd mapbox-gl-native/android/
./gradlew clean --refresh-dependencies
```

**Comment by ernest95** [comment]
I have same issue.bleege, tried your instructions but no luck.

**Comment by bleege** [comment]
@LuisBotero @ernest95 Thanks for trying to test the SNAPSHOT.  I created a simple app (see link below) that shows how to add the SNAPSHOT to an app.  Hopefully this helps!

https://github.com/bleege/MapboxSnapshot

**Comment by ernest95** [comment]
I'm still having these issue. It works on genymotion virtual devices but shows black screen on all android devices.

**Comment by LuisBotero** [comment]
@tobrun @ljbade @bleege Thank you very much for your help. The code is working for me and running fine.
![device-2015-10-29-110708](https://cloud.githubusercontent.com/assets/12969249/10824173/4d58cd5e-7e2d-11e5-8387-9bc532694c30.png)

**Comment by bleege** [comment]
Awesome @LuisBotero!  Thanks again for bringing this to our attention so that we could fix it.  We really appreciate it!  :rocket: :rocket:

**Comment by Pasha0093** [comment]
Hi have a black screen after execute 

`        CameraPosition.Builder cameraPosition = new CameraPosition.Builder()
                .target(position.toBoxLatLng())
                .bearing(bearing).tilt(90);
        if(!isZoomed){
            cameraPosition.zoom(16);
        }
        isZoomed = true;
        map.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition.build()), 25000, null);`

Using com.mapbox.mapboxsdk:mapbox-android-sdk:3.2.0@aar

**Comment by NonowPoney** [comment]
Hello,

I had the same problem, I saw the comment of Pasha0093 

 I noticed that I was using a "animateCamera"  in my onCreate() : 
```
    cameraPosition = new CameraPosition.Builder()
                .target(new LatLng(currentLocation.getLatitude(), currentLocation.getLongitude()))
                .zoom(currentZoom)
                .tilt(70)
                .bearing(0)
                .build();
```
`mapView.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), 5000, null);`

**I deleted this animateCamera in my onCreate()** and after that **I did not have black screen**

But also I use animateCamera for each new location of user (I've not delete it)


```
@Override
public void onResume() {
	 IntentFilter filterIntent = new IntentFilter(Constantes.BROADCAST_LOCATION_FILTER);
			bcReceiver = new BroadcastReceiver() {
				@Override
				public void onReceive(Context context, Intent intent) {              
					Bundle extras = intent.getExtras(); // on recup. le bundle
					Location temp = (Location) extras.get("NEW_LOCATION");					
					[..]
					updateMap(userPos.getLatitude(),userPos.getLongitude(),orientationCamera);
				}
			};
}	



private void updateMap(double latitude, double longitude, float orientCam) {

        currentZoom = calculZoom();
        markerUser.position(new LatLng(latitude, longitude));

        cameraPosition = new CameraPosition.Builder()
                .target(new LatLng(currentLocation.getLatitude(), currentLocation.getLongitude()))
                .zoom(currentZoom)// currentZoom
                .tilt(70)
                .bearing(orientCam)
                .build();

        mapView.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), 5000, null);
    }
```

**Comment by Pasha0093** [comment]
try move camera but it is without animation , about snapshot i cant integrate it in my project

**Comment by Pasha0093** [comment]
`mapView.moveCamera`

**Comment by NonowPoney** [comment]
I changed this : `mapView.animateCamera(CameraUpdateFactory.newCameraPosition(cameraPosition), 5000, null);`

by this : 

` mapView.setLatLng(new LatLng(currentLocation.getLatitude(), currentLocation.getLongitude()));`


the black screen remains for 1 to 2 seconds, then the map is comeback

**Comment by KaiWangCanada** [comment]
This happens to me when you try to move the camera before the mapview is fully loaded.

**Comment by tobrun** [comment]
This should not occur with `4.0.0` anymore. a workaround for `3.2.0` is to use the OnMapChangeListener and wait for the `DID_FINISH_LOADING_MAP` callback

**Comment by leocarona** [comment]
I started having issue with seen black screen instead of the tiles. It turned out that the app was reinstalled on my phone, so it lost the tiles that were previously loaded, and since my phone wasn't connected to any internet, the tiles were not been downloaded. A bit stupid, but I wanted to comment this here in case someone else gets to this page because they might be doing the same =)

**Comment by Insane-neal** [comment]
In China, VPN is required to visit mapbox server. Otherwise the screen is black. Do you have a local server?

**Comment by tobrun** [comment]
@Insane-neal, yes we do, see https://www.mapbox.cn/, reach out to support for more details

**Comment by zugaldia** [comment]
cc: @chriswu42

**Comment by chriswu42** [comment]
> In China, VPN is required to visit mapbox server. Otherwise the screen is black. Do you have a local server?

@Insane-neal we cannot guarantee complete stability hitting our `api.mapbox.com` endpoint from inside China due to implications with the Great Firewall. For faster and more stable services we recommend reaching out to us for using `api.mapbox.cn` endpoint hosted via servers based in China.

**Comment by Insane-neal** [comment]
@chriswu42 Thanks for the reply. I dont know how it works. So I have submitted a request, should someone contact me? It's been a day and nothing happens till now.
Since it is required to use an access token, which seems need a connection to cross the GFW, is this process stable?

**Comment by chriswu42** [comment]
@Insane-neal we currently don't provide free API access to our `api.mapbox.cn` endpoint since servers in China are very expensive to run, please reach out to our [sales team](https://www.mapbox.com/contact/sales/) if you decide to move forward here.

**Comment by sictiru** [comment]
I'm having a hard time with this library on a regular basis. The latest one is having a black map on v6.2.1. 
v6.3.0-beta.1 has the same issue + crashes inside telemetry. 
I'm calling all the lifecycles on the map.

The last stable version I didn't have problems with was 4.2.2 ( with a try catch because telemetry can handle android 8.0 since June 2018 only! ). 
Version 5.+ was freezing (ANR) the app or crashing on map render.

As you can tell I'm not happy about all of this
