### ISSUE TITLE
Too much drift pan resistance at z0–z1

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native#3655]
At z0 and z1, if you flick the map, it gets caught on something and even bounces back. Possibly related to #3588.

/cc @friedbunny

**Comment by tobrun** [comment]
FWIW noticing this on Android as well, adding `Android` label.

**Comment by 1ec5** [comment]
Maybe it’s related to the [call to `unwrapLatLng()`](https://github.com/mapbox/mapbox-gl-native/blob/cc47da5a15650c3f8ede9f7e253e4099dc61673f/src/mbgl/map/transform.cpp#L103) that I added in #3497. But it seems to work just fine for `flyTo()` (#3355).

**Comment by friedbunny** [comment]
Another case of panning "bouncing back" is when the map is tilted and you drag downward on the top forcefully — the map will shoot downward, rather than upward.

**Comment by tobrun** [comment]
we should maybe take the time to `git bisect` this issue to pinpoint it to a specific commit?

**Comment by tobrun** [comment]
I was able to pinpoint it to [this](https://github.com/mapbox/mapbox-gl-native/commit/d26b956a48dc2da9333b40d8d2c4371c63b372a2) commit.

```
d26b956a48dc2da9333b40d8d2c4371c63b372a2 is the first bad commit
commit d26b956a48dc2da9333b40d8d2c4371c63b372a2
Author: Minh Nguyễn <mxn@1ec5.org>
Date:   Sun Jan 10 17:28:21 2016 -0800

    [core] Cleaned up Transform
    
    Eliminated many redundant methods on Transform. Minimized usage of TransformState::x and TransformState::y. Added convenient constructors for AnimationOptions. When scaling, passing in view’s origin as the anchor no longer anchors the scaling operation at the view’s center. To specify no anchor, use NaN.
    
    Increased precision of worldSize(), now that it’s used much more heavily in transform methods.

:040000 040000 8f0b3b83dabb79ade17c755ba2937739429665ac 02de4fae20c3c2ed0bc85ebaaf9efe3e85f5f595 M	include
:040000 040000 183164f0f4d4ffd934d838d6e136af4d1780797f a3ebc9aeece1bcbdca2c3be0df87b54a86524d1d M	platform
:040000 040000 4f0133c1a47c3e37cff1af2606a64dfdeee6c68a 56b71bce1645fc572926fef5031b6c14958cf4d2 M	src

```

**Comment by 1ec5** [comment]
This was fixed in #4214.

**Comment by tobrun** [comment]
![gif-keyboard-12488273348198164312](https://cloud.githubusercontent.com/assets/2151639/13724005/b4e017f8-e844-11e5-94f8-f20798ce949e.gif)

**Comment by tobrun** [comment]
I retested on master with d64652f9bef9f1c252d197d3ceed638778540d6f, still an issue. See an example [here](https://youtu.be/5IKwiHXHTnc).

**Comment by 1ec5** [comment]
I don’t have access to that video, but I can’t reproduce the original issue in a980f725b88f1d6f05825dafff29dc6f422505d6 on iOS or OS X. Maybe what you’re seeing is unrelated?

**Comment by tobrun** [comment]
I just saw a difference between what I had seen during git bisecting and what we have now on master. Thinking a bit more about this I don't feel this is worth putting more time into. There are other priorities that are more important. Going to close.
