### ISSUE TITLE
[Android] [Bug] UserLocationView pinching issue 

### ISSUE THREAD

**Issue by mayardb** [mapbox/mapbox-gl-native#3698]
When I pinch the map, the UserLocationView is moving.

Since a video will be more understandable : [Video link](https://youtu.be/sfxyPJWXkg0)

**Comment by tobrun** [comment]
This is a known issue from the 3.1.0 release. 
This was resolved in #3661 / #3664.
You can use the SNAPSHOT to bypass this issue for now.
We are thinking about releasing a `3.1.1` release with this fix included.
See [this](https://www.youtube.com/watch?v=5z0ut09p430&feature=youtu.be) video from latest master/SNAPSHOT.

**Comment by mayardb** [comment]
Still reproducing it on the `head` of `master`.
Can you reopen the issue ?

Galaxy S4 mini
OS : 4.4.2

**Comment by mayardb** [comment]
Just tested again, and any gesture is moving the UserLocationView.

**Comment by tobrun** [comment]
@mayardb 

I'm unable to reopen this issue because of the following reasons:
 - issue is a programatic issue and unrelated to Android version or hardware
 - issue is not reproducible on testapp with latest changes on master
 - issue is not reproducible on a standalone app using latest SNAPSHOT
 - issue is reproducible with 3.1.0 version (as mentioned above and was fixed)
 - we do not provide support for forks (I have no issue looking into problems from forks but you should at least make this publicly available)

**Comment by mayardb** [comment]
* I indicate the version to help to reproduce (and have not been testing on other devices).
* I reproduce the issue on the testapp (see the video).
* I am pointing the `head`of `master` => is that the latest Snapshot ?
* I did not test the 3.1.0 version.
* I am pointing the `head`of `master` of `mapbox/mapbox-gl-native` repository.
