### ISSUE TITLE
Unrendered tiles / stencil mask overflow

### ISSUE THREAD

**Issue by jonbe242** [mapbox/mapbox-gl-native#4442]
_In later snapshots_ I have encountered a rendering issue on Android. See an example video here: https://dl.dropboxusercontent.com/u/1718104/device-2016-03-23-173401.mp4.

I do see some "stencil mask overflow" errors when this happens.
I only use two sources. The vector tile source has maxzoom set to 13. This seems to be related to when over zooming this sources data.

Any ideas to get around this would be greatly appreciated. I'd love to not have to do a git bisect in this one.

**Comment by jonbe242** [comment]
This seems to be related to #962. Funny thing is that I don't se this issue on iOS.
Android device is Samsung SM-T810.

**Comment by jonbe242** [comment]
Did a git bisect and found that the issue was introduced in commit 4edb2bc22281bc29822d46c3f39a9f99e40afa49 ([core] draw clipping masks from ClipIDGenerator rather than Sources).

**Comment by jonbe242** [comment]
Any ideas @kkaefer how to get around this?

**Comment by jonbe242** [comment]
Fixed in master now.

**Comment by mdakram** [comment]
Still getting this warning sometimes on android 5.1.0 when map rotates. @jonbe242
