### ISSUE TITLE
Android Offline Map Tile Count Always 0

### ISSUE THREAD

**Issue by tcolligan-ap** [mapbox/mapbox-gl-native#5525]
**Platform: Android**
**Mapbox SDK version: 4.1.0**

### Code Setup

1. Download sample project  https://github.com/mapbox/mapbox-android-demo.
2. Open `OfflineManagerActivity.java`
3. On line `268` find the following code block 
```
if (offlineRegions == null || offlineRegions.length == 0)
 {
     Toast.makeText(OfflineManagerActivity.this, "You have no regions yet.", Toast.LENGTH_SHORT).show();
     return;
 }
```
Paste the following code underneath the block.

```
offlineRegions[0].getStatus(new OfflineRegion.OfflineRegionStatusCallback()
                {
                    @Override
                    public void onStatus(OfflineRegionStatus status)
                    {
                        Log.d("TESTING", String.format(Locale.US, "Tile Size: %d", status.getCompletedTileCount()));
                    }

                    @Override
                    public void onError(String error)
                    {
                        Log.w("TESTING", error);
                    }
                });
```

### Reproduce
1. Build and Run code onto Android Device.
2. Download a map for offline use.
3. After download is completed tap `List` button.
4. Log will always print out `Tile Size: 0`

### Expected behavior
Tile size is non-zero number.

### Actual behavior
Tile size is zero.

**Comment by jfirebaugh** [comment]
Thanks for the report! This was previously reported in #5305, and fixed in #5475. The fix unfortunately didn't make it into 4.1.0, but will be in 4.2.0 and perhaps in 4.1.1, if we make a 4.1.1 patch release.

**Comment by snowpong** [comment]
@jfirebaugh As far as I can see, I still get 0 on both getCompletedTileCount() and getCompletedTileSize() on 4.2.2. Was this actually fixed and integrated into 4.2.0?
