### ISSUE TITLE
Tapping annotation within user location accuracy halo selects user location annotation

### ISSUE THREAD

**Issue by matrejek** [mapbox/mapbox-gl-native#5571]
**Platform:** iOS 9.3
**Mapbox SDK version:** 3.3.0 beta 3

### Steps to trigger behavior
(Screenshot below) 
 1. Add annotation near user location 
 2. Set it to show callout view
 3. When annotation is in range of user location accuracy (blue circle) it is impossible to show callout view (marker is not tappable). Instead of that we get callout for user location annotation

### Expected behavior

When annotation in blue circle is tapped it should show its callout. 

### Actual behavior

When annotation in blue circle is tapped user location annotation is presented. 

![aaa](https://cloud.githubusercontent.com/assets/1874050/16579222/ffe034a4-429e-11e6-8c32-2999e9fe3484.png)

**Comment by 1ec5** [comment]
This issue reproduces in v3.3.0 but not v3.2.0.

**Comment by 1ec5** [comment]
The regression was introduced in #1582. We now hit-test the user location annotation view based on its `layer.presentationLayer`, since the view can move around with implicit animation in response to the user location changing. We apparently should be hit-testing based on the `presentationLayer` of `_puckDot` or `_dotLayer`.

**Comment by friedbunny** [comment]
A fix for this should probably be done in conjunction with @frederoni’s refactor in #5573 or wait for that to land.

**Comment by 1ec5** [comment]
I think we can land a more targeted fix in v3.3.2.

**Comment by friedbunny** [comment]
Fixed by #5816.

**Comment by fabioknoedt** [comment]
The problem is still happening in the v3.3.3. I can't select an annotation within the user location's accuracy range.

**Comment by friedbunny** [comment]
True, #5816 excluded the pulsing halo layer but not the static accuracy ring. 

e4a9173a2a5c585dda3fa7a0f955cff1552f8d25 in #5882 includes a more comprehensive fix that specifically hit-checks the main dot. That will go in v3.4.0, but we could consider porting a similar fix to yet another patch release... @1ec5?

**Comment by fabioknoedt** [comment]
It would be awesome to have that fix as soon as possible. Now I'm stuck to the release v3.2.3 because of that. I want to start using MGLAnnotationView with the `selected` state support but I can't have this problem in the app. Thanks!

**Comment by friedbunny** [comment]
This was fixed in #5894 and is now available in the [v3.3.4 release](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.3.4).

**Comment by mrmacete** [comment]
Thank you!

**Comment by matrejek** [comment]
Thanks, it now works as it should.

**Comment by fabioknoedtbcgdv** [comment]
Cool, thanks!
