### ISSUE TITLE
Remove Guava from transitive dependencies

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#7129]
We're including Guava as a transitive dependency via LOST. This increases unnecessarily the method count and it doesn't affect LOST functionality if removed https://github.com/mapzen/lost/issues/58. Let's add a Gradle rule to remove it explicitly.

Note that this has already been fixed in LOST 2.0 https://github.com/mapbox/mapbox-gl-native/issues/6537 and won't be necessary once we upgrade.

/cc: @cammace @tobrun

**Comment by zugaldia** [comment]
cc: @Guardiola31337

**Comment by zugaldia** [comment]
Fixed via #7135.

**Comment by niedzielski** [comment]
@zugaldia, o/ I believe this fix was slated for v4.2.2 but I'm still seeing Guava as a dependency when specifying the v4.2.2 respository aar dependency instead of the project. For example, in the MapboxGLAndroidSDKTestApp app, `gradlew :MapboxGLAndroidSDKTestApp:dependencies` shows no Mapzen dependency on Guava. However, change the dependency:

```groovy
    // comment out project
    // compile(project(':MapboxGLAndroidSDK')) {
    //     transitive = true
    // }

    // add aar dependency from repository
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:4.2.2@aar') {
        transitive = true
    }
```

And now Mapzen depends on `com.google.guava:guava:18.0`. Can we reopen this issue?

**Comment by zugaldia** [comment]
@niedzielski Thanks for the report. Could you check `5.0.0-beta.1` released today https://github.com/mapbox/mapbox-gl-native/issues/8051? We've finally upgraded to LOST 2.0.0 which only includes Guava as a test dependency.

**Comment by niedzielski** [comment]
@zugaldia, cool! v5.0.0-beta.1 appears to be correct. Thanks :]

**Comment by zugaldia** [comment]
@niedzielski thanks for the 👀 !
