### ISSUE TITLE
MGLAnnnotation attach to screen when move map

### ISSUE THREAD

**Issue by iBinh** [mapbox/mapbox-gl-native#7558]
**Platform:** iOS
**Mapbox SDK version:** ios-v3.4.0-beta.6

### Steps to trigger behavior

 1. Add annotation to MGLMapView
 2. Move the map
 

### Actual behavior
Annotation attached to screen
Here's video
https://www.youtube.com/watch?v=6oiXv-xk03A&feature=youtu.be
@1ec5

**Comment by andrewstay** [comment]
Reproducible in **ios-v3.4.0-beta.5** too.

**Comment by 1ec5** [comment]
If this regression was introduced in beta 5, that would implicate #7423, which was intended to fix a similar issue.

/cc @boundsj

**Comment by boundsj** [comment]
I can indeed reproduce a similar issue because of the changes in #7423. I've proposed a fix for that in https://github.com/mapbox/mapbox-gl-native/pull/7626. The issue is that our attempt in #7423 to clear up a magic / undocumented value with `presentationLayer` introduced a new bug that manifested as shown in the video above when an annotation view was added outside of the viewport.

**Comment by boundsj** [comment]
This should be fixed by #7626

**Comment by Gerz-inc** [comment]
@boundsj this merge did not fix the problem. But in my case, it start from beta 3. Beta 1 work correct. Beta 2 - I can't test.

**Comment by boundsj** [comment]
@Gerz-inc I don't think I can reproduce this and the repro steps you've provided above are not detailed enough. Can you please share a code sample that reproduces the problem?

**Comment by l2comdev** [comment]
From what I've tested, when the annotation pans off the mapview it appears to be placed to the left outside the mapview frame multiplied by the annotation width. If the width of the annotation is 1px then the annotation sits on the edge of the screen as shown in @Gerz-inc gif, if the annotation width is say 20px then it is placed much further to the left of the map and is not visible.

**Comment by Gerz-inc** [comment]
@l2comdev, yes it's true! When I set the frame size up to 2x2px everything was fine

**Comment by boundsj** [comment]
@Gerz-inc @l2comdev I can reproduce this if I create an annotation view with a frame that is much smaller than some content it holds (like, a 2x2 annotation view frame that holds a UIImage of a car that is 28x28). However, I don't think there is a great way to solve for this edge case in the SDK. Especially for the case where views are added offscreen and the presentation layer is not available (see https://github.com/mapbox/mapbox-gl-native/pull/7626).

For several reasons, using a view large enough to hold its contents (like images) is 👍 . I'm going to keep this closed.

**Comment by l2comdev** [comment]
@boundsj  I agree, I initially discovered this when I was trying to make not selectable by making its frame 1x1. Is there a way to set this in the SDK?

**Comment by boundsj** [comment]
> make an annotation not selectable 

If you are using `MGLAnnotationView`s, you could use the `isEnabled` property (of `UIView`) for this purpose. If you want to allow selection but control if a callout view is displayed, you can override and add custom logic to `-[MGLMapViewDelegate mapView:annotationCanShowCallout:]`.
