### ISSUE TITLE
Update to stable version of LOST 

### ISSUE THREAD

**Issue by zugaldia** [mapbox/mapbox-gl-native#8939]
With https://github.com/mapbox/mapbox-gl-native/pull/8872 and https://github.com/mapbox/mapbox-java/pull/457 we're updating to a SNAPSHOT version of LOST in order to be able to troubleshoot https://github.com/mapbox/mapbox-java/issues/401.

Before we publish 5.1.0 final we need to make sure we update the code to a stable version of LOST, either 2.3.0, or downgrade to the latest 2.2.x stable.

cc: @tobrun @cammace

**Comment by tobrun** [comment]
Adding here that we also need to bump to stable versions of the MAS dependencies

**Comment by zugaldia** [comment]
Closed via https://github.com/mapbox/mapbox-gl-native/pull/9112.

**Comment by tobrun** [comment]
Reopening this as we are now depending on a SNAPSHOT build of LOST since https://github.com/mapbox/mapbox-gl-native/pull/9142 got merged to the release branch.

**Comment by zugaldia** [comment]
3.0.1 patch release landed on https://github.com/mapbox/mapbox-gl-native/pull/9302.

**Comment by krsticdragan** [comment]
Hi, I just wanted to report you that I have updated to a latest build 5.1.0-beta.5 and im still getting DeadObjectException and Location update after client was dissconnected. Unfortunatly I cant catch the behivour what cause this exceptions, it happens random thru application.

**Comment by zugaldia** [comment]
@krsticdragan I don't think https://github.com/mapzen/lost/issues/218 is fixed with the latest patch release. Still, please do share as much information as you can to help us reproduce the problem.

**Comment by joaopedro1520** [comment]
The problem is still not fixed with this version, I'm still getting tons of crashes after this update

**Comment by joaofyz** [comment]
Hi @zugaldia @tobrun ,

We are using the 5.1.0-beta.5 version and we are still getting this crash in our app.

We had 1500 crashes since we updated to this version, 84% of them in the android versions 6 and 7.

`Fatal Exception: java.lang.RuntimeException: android.os.DeadObjectException
       at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(SourceFile:78)
       at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(SourceFile:196)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
       at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
       at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:249)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:628)
       at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(SourceFile:104)
       at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(SourceFile:76)
       at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(SourceFile:196)
       at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
       at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
       at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:249)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)`

**Comment by tobrun** [comment]
@joaofyz thank you for the report. I would highly insist not shipping beta versions of our SDK in production. These pre releases are for test purposes only. Feel free to comment on the actual issue tracking that this [here](https://github.com/mapzen/lost/issues/218).

**Comment by zugaldia** [comment]
@joaopedro1520 @joaofyz to insist on what @tobrun just mentioned, the latest patch release of LOST fixes https://github.com/mapzen/lost/issues/213 but it does not fix https://github.com/mapzen/lost/issues/218. Please do report any information that could help us reproduce this issue on https://github.com/mapzen/lost/issues/218.

**Comment by krsticdragan** [comment]
@zugaldia @tobrun I hope this info could help you. In my project im not using LOST, im using only LocationManager and setMyLocationEnabled method. Crashes still happends randomly from time to time with no obvious rule.
