### ISSUE TITLE
animateCamera(CameraUpdateFactory.newLatLgBounds... only working the first time as expected

### ISSUE THREAD

**Issue by johanneslaubermoovel** [mapbox/mapbox-gl-native#9751]
**Platform:** Android
**Mapbox SDK version:** 5.1.1

### Steps to trigger behavior
fun MapboxMap.zoomToPolylines(latLngs: List<LatLng>) {
        val builder = LatLngBounds.Builder()
        for (latLng in latLngs) {
            builder.include(latLng)
        }
        animateCamera(CameraUpdateFactory.newLatLngBounds(builder.build(), 40.dpToPx()))
}

Call this methods 2 time with the exact same list of LatLngs

### Expected behavior

Zooms both times to the latlngs of the polylines

### Actual behavior

The first zoom is correct the second one has a big padding to the top and the right

**Comment by tobrun** [comment]
Thank you for reaching out, this is fixed with https://github.com/mapbox/mapbox-gl-native/pull/9391 and is scheduled to be released with 5.1.3, which is aimed to be released next week.

**Comment by johanneslaubermoovel** [comment]
I've updated to 5.1.3, but the problem is still there. Can you please check it?

**Comment by tobrun** [comment]
Adding a note here from https://github.com/mapbox/mapbox-gl-native/issues/9672#issuecomment-325310017:

> If I'm not mistaken, the fix is available in v5.1.3.
I can confirm that we no longer see the weird "added" padding.
However, it seems that the top padding is ignored when changing the camera bounds.
The bottom padding is correctly used.

**Comment by johanneslaubermoovel** [comment]
setPadding is working correctly since 5.1.3, but zoomToBounds still isn't for me

**Comment by tobrun** [comment]
Validated both on master and release branch with code similar to OP:

```java
  private static final LatLngBounds BOUNDS = new LatLngBounds.Builder()
    .include(ANDORRA)
    .include(LUXEMBOURG)
    .include(MONACO)
    .include(VATICAN_CITY)
    .include(LIECHTENSTEIN)
    .build();

    ...

        mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
          @Override
          public void onMapClick(@NonNull LatLng point) {
            int px = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 40, getResources().getDisplayMetrics());
            mapboxMap.animateCamera(CameraUpdateFactory.newLatLngBounds(BOUNDS, px));
          }
        });

```

Before clicking the map:

![image](https://user-images.githubusercontent.com/2151639/30315432-3a777716-97a4-11e7-830d-53879834a321.png)


After clicking the map:

![image](https://user-images.githubusercontent.com/2151639/30315450-490faf46-97a4-11e7-889e-a89842ed7447.png)


After clicking the map again:

![image](https://user-images.githubusercontent.com/2151639/30315460-5600feb2-97a4-11e7-9ab0-5884e6eca780.png)

Feel free to provide more context/code to help reproduce but closing this for now as not reproducible.

**Comment by johanneslaubermoovel** [comment]
Can you try to add padding to map first.

`
mapboxMap.setPadding(0, 0, 0, 200)
mapboxMap.setOnMapClickListener(new MapboxMap.OnMapClickListener() {
          @Override
          public void onMapClick(@NonNull LatLng point) {
            int px = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 40, getResources().getDisplayMetrics());
            mapboxMap.animateCamera(CameraUpdateFactory.newLatLngBounds(BOUNDS, px));
          }
        });`

**Comment by tobrun** [comment]
Yes, here is the result (code from master), clicking the map multiple times results in the same position:

![ezgif com-video-to-gif 23](https://user-images.githubusercontent.com/2151639/30421401-f3330560-993c-11e7-9713-53b6f4542a3b.gif)

**Comment by johanneslaubermoovel** [comment]
Now I found the problem, in my case the map was tilt before zooming to bounds.

In the video you see if the map is untilt everything works (well the border part get somehow cutted but thats not a big deal), but as soon as it is tilt it zooms somewhere else entirely 

https://youtu.be/v8jU3GUqQtU

(The code is in kotlin)

```  
zoomto.setOnClickListener {
            val latLng1 = LatLng(48.764183, 9.1668824)
            val latLng2 = LatLng(48.7648268, 9.1751567)
            val latLng3 = LatLng(48.7696245, 9.1717453)

            val latLngs = LatLngBounds.Builder()
                    .include(latLng1)
                    .include(latLng2)
                    .include(latLng3)


            val polylineOptions = PolylineOptions().apply {
                color(Color.GREEN)
                width(10f)
                add(latLng1)
                add(latLng2)
                add(latLng3)
            }

            (activity as MainActivity).map_view.getMapAsync { map ->
                map.animateCamera(CameraUpdateFactory.newLatLngBounds(latLngs.build(), 0))
                map.addPolyline(polylineOptions)
            }
        }
```

**Comment by olsisaqe** [comment]
[Here](https://github.com/mapbox/mapbox-gl-native/issues/9751#issuecomment-328779601) you should try to animate the camera and set the padding at the same time very fast.
