### ISSUE TITLE
MGLAnnotationView's annotation property is nil -> crash

### ISSUE THREAD

**Issue by RomainQuidet** [mapbox/mapbox-gl-native#9974]
**Platform: iOS 10**
**Mapbox SDK version: 3.5.2**

We can't reproduce this problem on our own, but we've got some crashes from our users.
It states that the AnnotationView's annotation property is nil. We do not touch this property in our app, so the bug lies in the SDK.

Incident Identifier: 04251B85-3F09-4A8D-9C7E-00F0FA54F776
CrashReporter Key:   A33FBC0F-4D3D-4724-B3A0-3DF19D7F504B
Hardware Model:      iPhone5,3
Process:         Mappy [713]
Path:            /var/containers/Bundle/Application/B9D4AA2F-82E9-44A4-A2EB-DAB2BBEA8F3A/Mappy.app/Mappy
Identifier:      com.mappy.Mappy
Version:         6.1734.1 (6.1734.1.2)
Code Type:       ARM
Parent Process:  ??? [1]

Date/Time:       2017-08-24T09:40:56Z
Launch Time:     2017-08-24T09:37:09Z
OS Version:      iPhone OS 10.3.3 (14G60)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x1d431acc
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Annotation view's annotation property should not be nil.'

Last Exception Backtrace:
0   CoreFoundation                       0x1dc63b3d __exceptionPreprocess + 129
1   libobjc.A.dylib                      0x1ceeb067 objc_exception_throw + 36
2   CoreFoundation                       0x1dc63a85 +[NSException raise:format:] + 106
3   Mappy                                0x00ee2f21 std::__1::unordered_map<unsigned int, MGLAnnotationContext, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, MGLAnnotationContext> > >::at(unsigned int const&) + 1282
4   Mappy                                0x00ee4f7f std::__1::unordered_map<unsigned int, MGLAnnotationContext, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, MGLAnnotationContext> > >::at(unsigned int const&) + 9568
5   UIKit                                0x2301d5e1 -[UIGestureRecognizer _shouldBegin] + 930
6   UIKit                                0x22ec541b -[UIGestureRecognizer setState:] + 220

**Comment by boundsj** [comment]
This sounds like https://github.com/mapbox/mapbox-gl-native/pull/8755 that should have been fixed by https://github.com/mapbox/mapbox-gl-native/pull/9025 that was released in https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.0. Since you say above you are using Mapbox iOS Maps SDK `v3.5.2`, can you please update to the latest version that is currently [v3.6.4](https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v3.6.4)

**Comment by RomainQuidet** [comment]
Hi,
We've updated to 3.6.4. I'll see if it solves the issue !

**Comment by olegwn** [comment]
I still get this from time to time without a reason and it's really annoying. 

**Platform: iOS 11.x**
**Mapbox SDK version: 6.1.2-beta**


When I click on an active PointAnnotation I get this crash:

```
2018-06-20 08:03:56.770685+0300 DaterReactNative[935:163067] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Annotation view's annotation property should not be nil.'
*** First throw call stack:

(0x182736fd8 0x181198538 0x182736f20 0x1020b80f4 0x1020ba0cc 0x1889f516c 0x188896770
 0x188a0d704 0x188a0d5b4 0x188a0d4cc 0x188e38c2c 0x188e2a928 0x188e2b258 0x188e2a5a8
 0x1888957e8 0x188866418 0x18905ff64 0x18905a6c0 0x18905aaec 0x1826e5424 0x1826e4d94 0x1826e29a0 0x182612d94 0x18407c074 0x1888cb130 0x1000c3ab0 0x18162159c)
libc++abi.dylib: terminating with uncaught exception of type NSException```
